### PR TITLE
Add ability to check if layout contains region

### LINKED ISSUE #2594: RegionManager#hasRegion(regionName)
I was surprised to find that this doesn't exist!

`return Boolean(this.getRegion(regionName));`

Also, it goes without saying, but it should be added to the LayoutView prototype.

### PR DESCRIPTION
**Pull request by jisaacks**
fixes #2594
Also see #2607

### CODE REVIEW

**Comment by megawac** [comment]
Looks good :+1:

**Comment by ahumphreys87** [comment]
lgtm :+1:

**Comment by ahumphreys87** [comment]
manually merged

**Comment by jmeas** [comment]
If we don't plan to get rid of RegionManager in v3, then this method should prob. be added to the RegionManager instead and proxied like the other methods.

**Comment by ahumphreys87** [comment]
@jmeas yeah we should keep this that in mind - Im quite keen on getting rid of it though. Especially now that _all_ views have `regions` I can't think of a major use case.

Also when #2625 lands it will clear the way to kill `CompositeView`  - we can replicate its functionality with a `region` in `View`. The dream of 2 views will become a reality!

**Pull request closed without merging**
