### PR TITLE
Adding an array-based syntax for Behaviors

### LINKED ISSUE #2366: Add alternative array syntax for Behaviors
As I've started to use Behaviors more, I've noticed that the current syntax for binding Behaviors to Views is optimized for a namespace based method of storing Behaviors.  As somebody who uses a module system (AMD and ES6 modules in my case), and uses several Behaviors that don't accept options, I end up writing extra code every time.  Specifically in situations like this

```javascript
import * as Mn from 'marionette';
import * as ValidationBehavior from 'behaviors/validation';
import * as KeymapBehavior from 'behaviors/keymap';
import * as WarnOnDestroyBehavior from 'behaviors/warn';

let ExampleView = Mn.LayoutView.extend({
    behaviors: {
        validation: {
            behaviorClass: ValidationBehavior,
        },
        keymap: {
            behaviorClass: KeymapBehavior
        },
        warn: {
           behaviorClass: WarnOnDestroyBehavior,
           message: 'Are you sure you want to delete this?'
        }
    },
});

export default ExampleView
```

So in this case validation, keymap, and warn are all unnecessary names that aren't used and don't need to be anything in particular.  They're basically just boilerplate/fluff.  I also have to keep typing behaviorClass and the object syntax even though classes are my primary way of defining behaviors, and I often don't need additional options.  It would be much nicer if I could write that code like this instead:

```javascript
import * as Mn from 'marionette';
import * as ValidationBehavior from 'behaviors/validation';
import * as KeymapBehavior from 'behaviors/keymap';
import * as WarnOnDestroyBehavior from 'behaviors/warn';

let ExampleView = Mn.LayoutView.extend({
    behaviors: [ValidationBehavior, KeymapBehavior, {
      behaviorClass: WarnOnDestroyBehavior,
      message: 'Are you sure you want to delete this?'
    }],
});

export default ExampleView
```

Instead of a big object and a bunch of boilerplate, I just pass the Behaviors as an array that accepts either a Behavior class, or an object that is defined the same way Behaviors are defined now.  So I avoid the unnecessary keys, and Behaviors that don't receive options can avoid all of the boilerplate altogether.

I'm happy to whip up a PR for this, I just wanted to get feedback first.  Note I'm proposing this as an additional syntax, not a breaking change.

### PR DESCRIPTION
**Pull request by benmccormick**
Add an array based syntax for attaching Behaviors to Views.  

Would close #2366.

### CODE REVIEW

**Comment by benmccormick** [comment]
I included my improve behavior documentation PR in here as well since I didn't want to deal with the merge conflicts involved in that, but I can pull it out or smash it into the other commit if people prefer.  That was a separate PR #2365

**Comment by jasonLaster** [comment]
behavior docs are in! great job

**Comment by benmccormick** [comment]
@jasonLaster thanks!   So that got merged into master, and this is against minor, so whats the procedure for how stuff migrates from master to minor?  It will make it easier for others to review this pull request if that stuff gets pulled out of the diff.

**Comment by samccone** [comment]
I keep minor on top of master. We can cherrypick the SHA onto minor and it will go away when i rebase of of master

**Comment by JSteunou** [comment]
Ho god +1, so sad it did not reach 2.4 :p

**Comment by samccone** [comment]
oh man @benmccormick mind getting a rebase on this for us?

**Comment by benmccormick** [comment]
@samccone yep, rebased and updated to comply with jscs.

**Comment by jasonLaster** [comment]
:+1: Nice work @benmccormick!

**Comment by samccone** [comment]
in it goes

thanks again @benmccormick

**Comment by benmccormick** [comment]
Awesome!  Thanks all.

**Comment by thejameskyle** [comment]
Hmm, sorry I didn't tune into this sooner. This might be a bad idea for inheritance, since there is no way you can easily inherit now without implementaion knowledge about the parent class.

This is already complicated enough:
```js
var MyView = AnotherView.extend({
  behaviors: function() {
    return _.extend(_.result(AnotherView.prototype, 'behaviors'), {
      // more behaviors
    });
  }
});
```

This is a complete disaster:
```js
var MyView = AnotherView.extend({
  behaviors: function() {
    var behaviors = _.result(AnotherView.prototype, 'behaviors');
    var myBehaviors = {
      // more behaviors
    };

    if (_.isArray(behaviors)) {
      return behaviors.concat(_.values(myBehaviors));
    } else {
      return _.extend(behaviors, myBehaviors);
    }
  }
});
```

**Pull request merged**
