### PR TITLE
delete view._parent after destroying view

### PR DESCRIPTION
**Pull request by denar90**
### Proposed changes
 - `delete view._parent` should be after `destroy` because when [destroy](https://github.com/marionettejs/backbone.marionette/blob/next/src/mixins/view.js#L172) is calling, it's calling region `empty` method which is deleting [view._parent](https://github.com/marionettejs/backbone.marionette/blob/next/src/region.js#L223).
So when `_triggerEventOnParentLayout` was called childView doesn't have parent so all [this](_triggerEventOnParentLayout) logic which is responsible for `childViewEvents` wasn't run.

Link to the issue:
#3045

### CODE REVIEW

**Comment by paulfalgout** [comment]
I think the most important part of this PR will be making a test to prove the solution.  I'm not certain that this change will fix the issue.  It seems like the delete is essentially happening at the same time.

**Comment by paulfalgout** [comment]
👍

**Comment by JSteunou** [comment]
@denar90 could you squash your commits please?

**Comment by paulfalgout** [comment]
Github will let you squash on merge now fwiw

**Comment by JSteunou** [comment]
Hoooo that's a very nice feature!

**Comment by JSteunou** [comment]
Loving it! I already forgot how to do it in command line :D

**Pull request merged**
