### PR TITLE
Lock down dependencies

### PR DESCRIPTION
**Pull request by paulfalgout**
Some minor version broke the build.  We should just manually update dependencies when we need to.
And update jQuery to v3

### CODE REVIEW

**Comment by rafde** [comment]
Out of curiosity, do you happen to know which dep broke the test?

**Comment by rafde** [comment]
Also, seems like this repo needs something like greenkeeper.

**Comment by paulfalgout** [comment]
not certain.. doesn't seem fun to track down either.
one of these:
```
babel-core                        6.7.0       6.13.2  6.13.2  babel-core
babel-eslint                      6.0.4        6.1.2   6.1.2  babel-eslint
babel-polyfill                    6.6.1       6.13.0  6.13.0  babel-polyfill
babel-preset-es2015              6.3.13       6.13.2  6.13.2  babel-preset-es2015
babel-preset-es2015-rollup        1.1.1        1.2.0   1.2.0  babel-preset-es2015-rollup
babel-register                    6.4.3       6.11.6  6.11.6  babel-register
chai                              3.4.0        3.5.0   3.5.0  chai
eslint                            3.2.2        3.2.2   3.3.0  eslint
gulp                              3.9.0        3.9.1   3.9.1  gulp
gulp-filter                       3.0.1        3.0.1   4.0.0  gulp-filter
gulp-istanbul                     1.0.0        1.1.0   1.1.0  gulp-istanbul
gulp-mocha                        3.0.0        3.0.1   3.0.1  gulp-mocha
gulp-plumber                      1.0.1        1.1.0   1.1.0  gulp-plumber
mocha                             3.0.0        3.0.2   3.0.2  mocha
rollup                           0.34.3       0.34.8  0.34.8  rollup
run-sequence                      1.1.5        1.2.2   1.2.2  run-sequence
sinon                            1.17.2       1.17.5  1.17.5  sinon
```

**Comment by scott-w** [comment]
Looks good to me 👍

**Pull request merged**
