### PR TITLE
implement bindRequests on views

### PR DESCRIPTION
**Pull request by wesmangum**
### Proposed changes
 - implementation of `bindRequests` on views for potential solution to "sinking" events down to child views. 
- Provides consistency for the 2-arg vs. 3-arg nature of `bindRequests` and `bindEvents`.

Link to the issue: https://github.com/marionettejs/backbone.marionette/issues/2956

### CODE REVIEW

**Comment by paulfalgout** [comment]
I think this is good.  Looking into it a bit further I think that all four bind imports can be removed from https://github.com/marionettejs/backbone.marionette/blob/master/src/mixins/radio.js since they're now on the common mixin and we don't export the radio mixin for other use.  Doesn't change much really, but we don't really benefit from having it duplicated.

**Comment by bazineta** [comment]
Entirely possible that I'm missing something, but it's not evident to me that there's not a leak here. 

That is, it seems that one would call this.bindRequests(), expecting that there'd be automatic unbinding in the `destroy` as in this.bindEvents(), but I don't see where that would be the case.

**Comment by bazineta** [comment]
A fiddle against the current Mn to demonstrate my confusion: https://jsfiddle.net/orj1sckr/5/

**Comment by JSteunou** [comment]
I think you're right, if the other bindings get unbind automatically, this one should also be unbind, or have a different name.

**Comment by paulfalgout** [comment]
It is impossible to prevent events from being unbound on destroy.

**Pull request merged**
