### PR TITLE
bug fix for #2395

### PR DESCRIPTION
**Pull request by dkurucz**

### CODE REVIEW

**Comment by sentientnebula** [comment]
I just adjusted my code to 2.4's new buffering logic.   Your proposed patch would break me again by bypassing _buildBuffer.  This kind of reinforces my point about needing a standardized method/approved point for tweaking Collection/CompositView output so you don't need to worry about having the rug pulled out from under you with every update/patch.

See:   <a href="https://github.com/marionettejs/backbone.marionette/issues/2388">#2388</a>

**Comment by dkurucz** [comment]
Overriding methods starting with underscore is dangerous and it would be unwise to assume that version updates will continue to support such things.  The documentation hinted at a convention for changing the content of a CollectionView by overriding the attach, so I figured unless marionette actually gains efficiency by changing the buffer logic, they should just stick to the standard that worked well and then encourage its use in the documentation.  Currently I don't see either happening.

**Comment by sentientnebula** [comment]
Too late for for sticking with the standard.  The previous recommendation was to override AttachHTML, but the new buffer logic added in 2.4 makes that no longer a good place for the reasons described in my post.

_buildBuffer, however, becomes a good spot for custom buffer building logic.  That is why I recommended it be renamed buildBuffer (no underscore).

**Comment by samccone** [comment]
hey @dkurucz @sentientnebula I will dig into this, been really slammed with things at the moment, if you would not mind could you possibly find which commit caused this regression and we can get a fix out instead of layering on "patches"

Thanks so much for the great find and PR @dkurucz 

I can assure you we don't want to break peoples code, and we want to be consistent, the last thing we want to do is to cause you guys issues.

**Comment by sentientnebula** [comment]
Might need to think about this one a bit :)  Buffering code was changed in the context of adding a major feature.  There are also a couple of other open issues related to this change, so you'll want to look at everything together.

*For some reason, I keep referring to _createBuffer as _buildBuffer.  The new function in question is _createBuffer.

I actually like the change so long as it is renamed createBuffer (no underscore), so it can be reliably overridden to tweak how collections are formatted just prior to attachment.  It's a very nice spot for it.
 
<a href="https://github.com/marionettejs/backbone.marionette/commit/0dd7775ae6e261eb3666aa482f9660462065c756">#0dd7775 Allow custom sort comparator for CollectionView</a>

**Comment by dkurucz** [comment]
Just throwing in my $0.02, devs should probably not be responsible for creating and changing the buffer itself, this should be handled by marionette.  The developer should use the resulting buffer content as they see fit inside the attachBuffer override during the render phase.  This was a good idea from the beginning, although I am not sure if there were plans to enhance this part of the framework.  I'm not sure which major feature you are referring to, but it is at the moment inconclusive whether my changes would negatively affect any plans for its implementation.

The problem with changing _createBuffer to createBuffer is that the framework will then need to support two exclusive entry points into the CollectionView content generation phase (render), when really, one should be all that is needed, and ideally, if a better idea/feature/view comes into play down the road, none at all would be needed.  I included my changes into a 2.4.1 build and into my project, and the fixes are working great and are indeed backwards compatible.

@sentientnebula would there be problems going back to your original design if this fix were to be rolled in?

**Comment by jasonLaster** [comment]
ping @cmaher, @ahumphreys87 mind taking a look

**Comment by ahumphreys87** [comment]
LGTM, @dkurucz nice work! Could you a some tests that prove the bug is there without this fix? This will stop this issue creeping back in again :)

**Comment by sentientnebula** [comment]
I think someone needs to line up all the issues together and make a top to bottom review of the collectionView/CompositeView code as a whole, instead of continuing to make out of context changes to bits and pieces of code with each point release.  That how this whole thing got started.

If you accept this request for 2.4.2, without thinking too hard, for example, there will be a request to change it back again in 2.4.3 to match the collectionView's implementation--or vice versa.  At the very least, change them both together.

Has anyone even asked cpjolicoeur why he decided to rebuild the buffer?

I still think there should be a mechanism provided to wrap/sub-group itemviews before attachment. attachement.

**Comment by sentientnebula** [comment]
Looking over cpjolicoeur's commit, it appears that his changes were to intended to delay creating the buffer until right before attachment in order to maximize flexibility to manipulate the children without having to duplicate effort (i.e.sorting, or in my case, grouping).  ChildViews were previously being buffered on the fly as children arrived, so any manipulation would require a rebuffer.

This proposed commit would pull the trigger a bit earlier and bake in the buffer right before it gets to attachBuffer--the place where most people would want to make their changes.

**Comment by paulfalgout** [comment]
> I think someone needs to line up all the issues together and make a top to bottom review of the collectionView/CompositeView code as a whole

:+1:

**Comment by jasonLaster** [comment]
Mind reopening this issue against 2.4.2 so it can go in as a bug fix? 

Also let's add a test to demonstrate the previous bug and the fix.

**Comment by ahumphreys87** [comment]
@dkurucz any word on this?

**Comment by dkurucz** [comment]
Yeah I will get to them this weekend.

**Comment by sentientnebula** [comment]
What exactly is being accomplished by calling _createBuffer, a step earlier other than reducing flexibility?

Actually, I'm not going to be effected by the change because I moved all the customization into _createBuffer, so it won't matter at what point _createBuffer is called.  This, however, is definitely not the recommended customization point.  If this change is accepted what will be the new recommended point to customize the buffer creation process without building the buffer twice?

The documentation says to override attachBuffer.

Now:

Just call your own custom method in place of the _createBuffer.
Your custom buffer method is called.
Standard _createBuffer is not.
Buffer is only built once.

After this patch:

`````
// You might need to override this if you've overridden attachHtml
-  attachBuffer: function(compositeView) {
+  attachBuffer: function(compositeView, buffer) {
     var $container = this.getChildViewContainer(compositeView);
-    $container.append(this._createBuffer(compositeView));
+    $container.append(buffer);
   },
`````
Standard Buffer is created BEFORE recommended override points of attachHTML/attachBuffer.  Too late to customize there now without duplicating effort.

New Recommendation:  ???
Create your own buffer and throw away the already created buffer (buffer created twice).   This seems like a big step backward.

Unless, of course, you override _createBuffer instead.  The problem with this is that _createBuffer is marked as a private method.  I don't think this patch should be accepted unless  _createBuffer is also changed to a public createBuffer method.

**Comment by ahumphreys87** [comment]
Closing in favour of #2494

**Pull request closed without merging**
