### PR TITLE
Do not bind render method in View classes

### LINKED ISSUE #2372: Stop binding render to the view
At view construction, we bind render to the view.
https://github.com/marionettejs/backbone.marionette/blob/master/src/view.js#L10

This is 
1. Generally unnecessary
2. Unexpected by new users of Marionette
3. Kind of weird
4. A problem when testing

``` js
var MyView = Marionette.ItemView.extend({
  initialize: function () {
      // yes, this could use modelEvents, but it's a general problem
      this.listenTo(this.model, 'change', this.render);
  }
});

describe('MyView', function () {
  it('calls render when the model changes', function () {
    var model = new Backbone.Model();
    sinon.stub(MyView.prototype, 'render');
    var view = new MyView({ model: model });
    model.set('foo', 'bar');
    expect(view.render).to.have.been.called;  // error! view.render is not a spy (it's a bound function that calls a spy) 
    expect(MyView.prototype.render).to.have.been.called; // the way we currently have to test this
  });
});
```

In v3, we should just remove the binding.

### PR DESCRIPTION
**Pull request by blikblum**
### Proposed changes
 - Do not bind render method in View and CollectionView
 - Adjust tests accordingly

Link to the issue:
Fixes #2372

### CODE REVIEW

**Comment by paulfalgout** [comment]
This is technically breaking.  Should probably wait until `v4`

**Comment by scott-w** [comment]
Looks good. I think it's worth adding a test from #2372 to test the behaviour is as we expect.

**Comment by paulfalgout** [comment]
I'm not sure a test is necessary TBH. This is a pretty oddball line to add.  We don't test that any other function isn't bound.  However this function like most do require that the function be called with the context.  I guess we could test that `myView.render === View.prototype.render`, but again that'd be a test we could apply to every function.

**Comment by blikblum** [comment]
Done

**Pull request merged**
