### PR TITLE
Set a specific port per travis sauce test

### PR DESCRIPTION
**Pull request by paulfalgout**
Attempting a further fix for https://github.com/marionettejs/backbone.marionette/issues/3343

### CODE REVIEW

**Comment by paulfalgout** [comment]
@denar90 doesn't look like that helped https://travis-ci.org/marionettejs/backbone.marionette/jobs/221618084

**Comment by paulfalgout** [comment]
Oh.. it's this: https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

**Comment by paulfalgout** [comment]
Ok this worked.. I'm going to go ahead and merge it.. we can fix it again if there's another issue.

**Comment by denar90** [comment]
👍

**Pull request merged**
