### PR TITLE
(don't merge review only) 2.4

### PR DESCRIPTION
**Pull request by samccone**

### CODE REVIEW

**Comment by benmccormick** [comment]
Any chance we could work #2344 into this?

**Comment by jasonLaster** [comment]
yea, i think so

**Comment by samccone** [comment]
ping ping @marionettejs/marionette-core

**Comment by samccone** [comment]
I made demos
http://samccone.github.io/marionette-2.4-demos/

:+1: need to inline the important code... but that is simple yay exciting

**Comment by jasonLaster** [comment]
Nice!

**Comment by ahumphreys87** [comment]
Lgtm :+1:

**Comment by samccone** [comment]
@jasonLaster @paulfalgout @kkemple ready for :eyes: fixed the ie8 issue

**Comment by kkemple** [comment]
:+1: so much

**Pull request merged**
