### PR TITLE
Check if filter is set

### PR DESCRIPTION
**Pull request by sdnetwork**

### CODE REVIEW

**Comment by samccone** [comment]
@sdnetwork thanks for the PR. mind adding a test case please

**Comment by ianmstew** [comment]
This is intended to fix #2606.

**Comment by ahumphreys87** [comment]
@sdnetwork this looks good, just needs a test that proves the bug fix and prevents a regression :smile:

**Comment by jridgewell** [comment]
I'm not sure why [lines 244-248](https://github.com/sdnetwork/backbone.marionette/blob/master/src/collection-view.js#L244-L248) are ever needed? Shouldn't the [original `#isEmpty`](https://github.com/sdnetwork/backbone.marionette/blob/master/src/collection-view.js#L236-L237) check have returned `true`?

**Comment by ahumphreys87** [comment]
@jridgewell i think its to catch the case where a filter "filters" all the children. The first is checking the collection which doesn't actually change with the filter

**Comment by JSteunou** [comment]
from #2661 I was wondering if 

> Should the isEmpty check on children is a filter is set, and if not, fall-back on collection && collection.length?

**Comment by jridgewell** [comment]
> Should the #isEmpty check on children is a filter is set, and if not, fall-back on collection && collection.length?

I think the issue is there isn't a performant way to determine if a filtered set is empty, without running the filter on all `n` models.

As it stands right now (and with this PR), `CollectionView#isEmpty` has lost its usefulness. It's no longer smart enough to handled a filtered collection, since we don't want that performance impact.

We could store the filtered models in an array and provide an API to access that filtered array. That'll take care of the performance impact, and allow `CollecitonView#isEmpty` to be useful again. But at that point, we're reinventing a `Collection`. :frowning: 

I think the real issue stems from where we've landed this functionality. It shouldn't be a view's responsibility to filter the collection's models, it should be the collection's. Using something like [VirtualCollection](https://github.com/p3drosola/Backbone.VirtualCollection) seems like an appropriate solution.

**Comment by ahumphreys87** [comment]
@jridgewell I see where you are coming from and I know there was a big discussion about where to land the filter functionality back in the original PR.

However, as things stand this PR fixes a bug - I'm :+1: for getting this into a 2.x release. Maybe we can look at how we implement `filter` differently in a major version? I think your right - it probably needs a rethink.

**Comment by ianmstew** [comment]
Manually merged via https://github.com/marionettejs/backbone.marionette/commit/a8771a4f5cd94d847d4e94db88dca26ea51a1acf.

**Comment by JSteunou** [comment]
Does it fix #2661 too?

**Comment by ianmstew** [comment]
@JSteunou good call!

Also, for future reference, the current solution is a nonbreaking stopgap.  The more comprehensive solution is already in `next` for 3.0: https://github.com/marionettejs/backbone.marionette/blob/2af55e5020da9d74c043bd5c121e1f95c45457d9/src/collection-view.js#L277-L285

**Pull request closed without merging**
