### PR TITLE
"event" missing from heading breaking index

### PR DESCRIPTION
**Pull request by paulfalgout**

### CODE REVIEW

**Comment by jasonLaster** [comment]
oh wow. that's so picayune!

**Comment by jmeas** [comment]
> picayune

**Comment by samccone** [comment]
> > picayune

**Comment by samccone** [comment]
> > > "the picayune squabbling of party politicians"

**Comment by thejameskyle** [comment]
> > > pikachu

**Comment by jmeas** [comment]
:zap: :mouse:

**Pull request merged**
