### PR TITLE
Remove _.isUndefined usage

### PR DESCRIPTION
**Pull request by anthony-redFox**
#2689

typeof more clear then void(0) and the same by performance.
https://jsperf.com/typeof-vs-undefined-check/12

### CODE REVIEW

**Comment by paulfalgout** [comment]
@megawac care to weigh in?  underscore switched to `=== void 0` from typeof and lodash is simply `=== undefined`

**Comment by anthony-redFox** [comment]
The undefined is not a reserved word, it can be used as an variable name in any scope other than the global scope. So `=== undefined` should be slow than `=== void 0` or `typeof` with scopes.

Underscore swhiched to `=== void 0` because of check ActiveX Objects from Internet Explorer.
We don't use ActiveX Objects.

**Comment by paulfalgout** [comment]
Ah, yeah in lodash I believe undefined is referring to a local `var undefined;`

**Comment by megawac** [comment]
I would suggest == null

**Comment by anthony-redFox** [comment]
@megawac  - my opinion it is not good idea, it is conflict with jshint with option 'eqeqeq',  and many misunderstanding contains '=='

**Comment by samccone** [comment]
I am ok with this

**Comment by jasonLaster** [comment]
@samccone which way do you propose
@anthony-redFox mind rebaing off of next. You'll get passing tests :)

**Comment by anthony-redFox** [comment]
@jasonLaster done

**Pull request merged**
