### PR TITLE
reassign view index on reorder

### PR DESCRIPTION
**Pull request by ahumphreys87**
Opening in favour of #2422

### CODE REVIEW

**Comment by ahumphreys87** [comment]
ping @marionettejs/marionette-core lets get this in

**Comment by jasonLaster** [comment]
:+1:

**Comment by cmaher** [comment]
:+1:

**Comment by sophietk** [comment]
:+1:

**Comment by jgerigmeyer** [comment]
Any chance of getting this into a minor release soon? Seems like a significant bug to leave hanging around.

**Comment by ahumphreys87** [comment]
@jgerigmeyer 2.4.2 is currently pending release - hopefully within the next day or so :)

**Pull request merged**
