### PR TITLE
Remove use of deprecated $.selector

### PR DESCRIPTION
**Pull request by JSteunou**
Mostly to initiate a discussion on that the thing.

linked to #2668

What is the nature of `this.el` at this point? Still a String? An Object? An Object with a nice `toString`?

### CODE REVIEW

**Comment by paulfalgout** [comment]
unfortunately it could be a string or a dom element.  It may be ok that it doesn't attempt to say what selector was used for the el...  For that matter the region has it's own cid now, so that could used as an identifier.  We should probably be utilizing those cids in errors more consistently.

**Comment by JSteunou** [comment]
Something like that?

**Comment by paulfalgout** [comment]
that works for me.

**Comment by JSteunou** [comment]
squashed

**Comment by paulfalgout** [comment]
This just needs the error's test updated.

**Comment by JSteunou** [comment]
meh tests are failing 

> Error: Cannot find module 'estraverse-fb'

**Comment by paulfalgout** [comment]
This is eslint.  We might need to set that dependency, though this was supposedly going to be fixed today.

**Comment by paulfalgout** [comment]
@JSteunou mind squashing this into a single commit, and I'll get this in.  Thanks!

**Comment by JSteunou** [comment]
aaaand squashed

**Pull request merged**
