### PR TITLE
Added Gitter Icon to the readme.md to help people join faster

### PR DESCRIPTION
**Pull request by XescuGC**
Sorry guys, I've made an auto-pull-request for thin from the Gitter App (#2305), this is the format i think it should have :)

### CODE REVIEW

**Comment by jmeas** [comment]
:+1:

**Comment by samccone** [comment]
I kinda want to roll my own gitter image service, one that matches the green that we have, and also shows the # of people in the room... thoughts?

ping @mydigitalself @suprememoocow

**Comment by samccone** [comment]
ok I chatted with the people at gitter and they said this is something they are working on, so lets merge this and iterate.

**Comment by samccone** [comment]
thanks @XescuGC manually picked in

**Comment by XescuGC** [comment]
It's a good solution until they implement the other approach.
Thanks to you for accepting it :smile:

**Pull request closed without merging**
