### PR TITLE
feat(behavior): override behavior ui with view ui

### PR DESCRIPTION
**Pull request by stephanebachelier**
Rebase on major as discussed in #2265 with explanations in #2266

### CODE REVIEW

**Comment by jasonLaster** [comment]
This looks good to me @stephanebachelier

**Comment by jasonLaster** [comment]
one error 
```
1) Behaviors behavior UI view should be able to override predefined behavior ui "before each" hook:
     TypeError: Cannot call method 'extend' of undefined
      at Context.<anonymous> (/home/travis/build/marionettejs/backbone.marionette/test/unit/behaviors.spec.js:329:47)
      at callFn (/home/travis/build/marionettejs/backbone.marionette/node_modules/mocha/lib/runnable.js:223:21)
      at Hook.Runnable.run (/home/travis/build/marionettejs/backbone.marionette/node_modules/mocha/lib/runnable.js:216:7)
      at next (/home/travis/build/marionettejs/backbone.marionette/node_modules/mocha/lib/runner.js:258:10)
      at Object._onImmediate (/home/travis/build/marionettejs/backbone.marionette/node_modules/mocha/lib/runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by thejameskyle** [comment]
It seems to me like behaviors shouldn't have access to the view.ui hash

**Comment by stephanebachelier** [comment]
@thejameskyle the idea is not for a behavior to access the view.ui but for any view to override any configuration predefined in a behavior ui. 
If needed I will build an example.

@jasonLaster I need to fix this falling test. Forgot to run the tests after the rebase on major.

**Comment by samccone** [comment]
:+1: to this improvement great call @stephanebachelier 
looks like your test is currently failing, just fix that up and we can get it in!

If you think that you will not have time to finish this up just let us know and we can pick it up, thanks for the work!

**Comment by stephanebachelier** [comment]
@samccone test fixed, it was failing because ItemView has been renamed to View

**Comment by jfairbank** [comment]
This looks good to me :+1:

**Comment by stephanebachelier** [comment]
If you are ok to accept this PR, I will add documentation. This small change needs to be documented.

**Comment by samccone** [comment]
hey @stephanebachelier more than willing to get this in, mind updating docs?

**Comment by jasonLaster** [comment]
so close! lets get this over the hump

**Comment by stephanebachelier** [comment]
@jasonLaster @samccone I update the doc

**Comment by jasonLaster** [comment]
@stephanebachelier I don't see the doc changes. Were they not pushed?

**Comment by stephanebachelier** [comment]
@jasonLaster I push docs today.

**Comment by stephanebachelier** [comment]
@jasonLaster I've updated the comments in the source file, hence the new commit, rebase on major, and added some documentation for behavior.
By the way the `ui` section was missing from behavior documentation.

**Comment by jasonLaster** [comment]
Thanks for the docs. 
:+1:

**Comment by jasonLaster** [comment]
Needs one more thumb

**Comment by samccone** [comment]
great work @stephanebachelier

**Pull request merged**
