### PR TITLE
Bump and build v3.0.0-rc1

### PR DESCRIPTION
**Pull request by paulfalgout**
If this is all good we'll need to make a release and publish with `v3.0.0-rc1`

### CODE REVIEW

**Comment by samccone** [comment]
:+1:

**Comment by JSteunou** [comment]
:confetti_ball:

**Comment by chchrist** [comment]
:cake:

**Comment by demonkoryu** [comment]
:feelsgood:

**Comment by MeoMix** [comment]
:fire:

**Pull request merged**
