### PR TITLE
Remove BB metal since it's not published on Bower

### PR DESCRIPTION
**Pull request by jdaudier**
Discovered this last night w/ @pascalpp at the [Marionette First-Time Contributor Workshop](http://www.meetup.com/Dancing-with-Marionette-js/events/223590256)

### CODE REVIEW

**Comment by megawac** [comment]
Wiser to just publish on bower?

**Comment by jdaudier** [comment]
@megawac Who would be able to do that?

**Comment by megawac** [comment]
Consider it done.

**Comment by jdaudier** [comment]
Great @megawac! Feel free to close this PR when you're done.

**Comment by megawac** [comment]
Ohp, had already registered it

**Comment by pascalpp** [comment]
strange: it shows up in the CLI:

```
$ bower search backbone-metal
Search results:

    backbone-metal git://github.com/marionettejs/backbone-metal.git
```

but not here:

<http://bower.io/search/?q=backbone-metal>

**Comment by megawac** [comment]
probably reindexs packages on some sort of cron job

**Pull request closed without merging**
