### PR TITLE
Add the removeChildView to documentation

### PR DESCRIPTION
**Pull request by lei-clearsky**
This fix the #2780.

### CODE REVIEW

**Comment by samccone** [comment]
:+1: awesome thanks a ton @lei-clearsky

**Comment by lei-clearsky** [comment]
Thanks @samccone! This is my second OSS pull request still a lot to learn :smile:  For the code example for removeChildView in documentation I just follow the buildChildView example and made the function a little shorter with comments. Please let me know if this is ok or need more changes. Thanks!

**Comment by lei-clearsky** [comment]
Thanks for the feedback @paulfalgout! I will work on the revision and update the PR!

**Comment by lei-clearsky** [comment]
Hey @paulfalgout I created an example of implementation below, does it look ok? Thanks!
```
// add some views to a CollectionView
var MyModel = Backbone.Model.extend({});

var MyCollection = Backbone.Collection.extend({
  model: MyModel
});
  
var MyView = Marionette.ItemView.extend({...});
  
var MyCollectionView = Marionette.CollectionView.extend({
  childView: MyView
});

var foo = new MyModel({name: "foo"});
var bar = new MyModel({name: "bar"});

var myCollection = new MyCollection([foo, bar]);

var myCollectionView = new MyCollectionView({
  collection: myCollection
});
  
myCollectionView.render();
  
var myView = myCollectionView.children.findByModel(foo);

// remove a child view myView  
myCollectionView.removeChildView(myView);

// check if the removed view still exist
console.log(myCollectionView.children.findByModel(foo)); // return undefined
console.log(myCollectionView.children.findByModel(bar)); // return a childView bar 
```

**Comment by paulfalgout** [comment]
maybe we can imply some of it:
```js

var myCollectionView = new MyCollectionView({
  collection: new Backbone.Collection([fooModel, barModel])
});

myCollectionView.render();

var myView = myCollectionView.children.findByModel(fooModel);

// remove a child view myView  
myCollectionView.removeChildView(myView);

// check if the removed view still exist
console.log(myCollectionView.children.findByModel(fooModel)); // return undefined
console.log(myCollectionView.children.findByModel(barModel)); // return a childView bar 
```

**Comment by lei-clearsky** [comment]
Really appreciate the feedback! I've updated the PR :)

**Comment by samccone** [comment]
woot great work @lei-clearsky :smile:

**Comment by paulfalgout** [comment]
:clap:

**Comment by lei-clearsky** [comment]
Thanks!! @samccone @paulfalgout :smile: :smile:

**Pull request merged**
