### PR TITLE
Fixing the naming inconsistency between child view attribute and event prefix #2194

### LINKED ISSUE #2121: Naming inconsistency between child view attribute and event prefix
I noticed that the child view attribute for `CollectionView`/`CompositeView` is camel cased like `childView:`, while child view events are prefixed with `childview` in lower case.

I think this needs to be fixed to be consistent. I've tripped on this a couple of times causing bugs when I've camel cased the event prefix.

### PR DESCRIPTION
**Pull request by SauloSilva**
Replacing the event name of prefix childview to childView

Fix #2121

### CODE REVIEW

**Comment by SauloSilva** [comment]
@samccone I made the requested changes

**Comment by SauloSilva** [comment]
@samccone I made the requested changes

**Comment by jasonLaster** [comment]
Awesome!

**Comment by samccone** [comment]
:ship:

**Comment by samccone** [comment]
@SauloSilva thanks so much for the work

**Comment by SauloSilva** [comment]
@samccone thanks man :D

**Pull request merged**
