### PR TITLE
adds support for Object.isDestroyed

### LINKED ISSUE #2620: Add isDestroyed flag to Mn.Object/Mn.Class
When an object is destroyed, it should be marked with `isDestroyed = true` in the same way that views are.

Use case: I have an object which calls one of its methods on a 5-second `_.delay` after being instantiated. If the object is destroyed in the mean time, that delayed method needs a way to detect that the object has been destroyed and return early.

Workaround: I've added an `onDestroy` method to my controller and applied the `isDestroyed` flag myself.

(I understand that Marionette.Object is getting replaced by Marionette.Class in a future version; the same issue applies.)

### PR DESCRIPTION
**Pull request by pascalpp**
[fixes #2620]

also adds 2 tests to object.spec.js

### CODE REVIEW

**Comment by pascalpp** [comment]
I'm not sure what to make of that build failure.

**Comment by pascalpp** [comment]
I think it was just a blip with curl. Is there a way to retrigger Travis?

**Comment by pascalpp** [comment]
@ahumphreys87 Can you review this PR and let me know if there's anything else I should do?

**Comment by jasonLaster** [comment]
@pascalpp you can bump it in travis in the top right

**Comment by jasonLaster** [comment]
looks good to me... thoughts crew?

**Comment by ahumphreys87** [comment]
:+1:

**Comment by ahumphreys87** [comment]
manually merged

**Pull request closed without merging**
