### PR TITLE
Fix LayoutView#showChildView returns `this` not region

### PR DESCRIPTION
**Pull request by cmisenas**
Resolves https://github.com/marionettejs/backbone.marionette/issues/2582

### CODE REVIEW

**Comment by cmisenas** [comment]
Woops fixing base.

**Comment by jasonLaster** [comment]
oops, looks like you need to rebase your local branch off of next

**Comment by jasonLaster** [comment]
hmm, still busted.

try doing this locally:
```bash
git checkout origin/next;
git pull --rebase
git checkout fix-layoutview-showchildview
git reset --hard next
touch "write some code"
git commit "fix"
grunt test
git push me  fix-layoutview-showchildview
```

**Comment by samccone** [comment]
was this behavior ever documented? what makes this a bug and not a breaking change?

**Comment by jasonLaster** [comment]
I don't think that we documented this behavior. 

I think it's fair to expect view methods to be fluent unless the return is implied. @jmeas, thoughts?

**Comment by jmeas** [comment]
I expected this to be released in v3.

**Comment by cmisenas** [comment]
Happy to start contributing @jmeas ! :)

**Comment by cmisenas** [comment]
Should I also submit a commit that documents this behavior?

**Comment by jmeas** [comment]
> Should I also submit a commit that documents this behavior?

That would be fantastic!

**Comment by cmisenas** [comment]
@jmeas is ^ ok?

**Comment by samccone** [comment]
@cmisenas when you are ready, just run an interactive rebase and squash this all into one commit.

thanks for the work :heart:

**Comment by ahumphreys87** [comment]
:+1:  great work @cmisenas

**Comment by jmeas** [comment]
> @jmeas is ^ ok?

Yes, this is awesome. Thanks so much @cmisenas!

**Comment by ahumphreys87** [comment]
@jmeas does this get you :+1: ?

**Comment by jmeas** [comment]
Yup. :+1:!

**Comment by ahumphreys87** [comment]
merged into next

**Pull request closed without merging**
