### PR TITLE
Remove bundled build for v3 and integrate babysitter.

### PR DESCRIPTION
**Pull request by paulfalgout**
This is kind of a last minute sizable change, but hopefully I can argue well enough for it.

Immediately this would resolve https://github.com/marionettejs/backbone.marionette/issues/3070 as there would be no bundled build.  Our bundled build is complicated.  It might be easier solved by switching everything to webpack, but I'm not 100% certain it'd be that much better.. we'd have to change everything quite a bit and our output would look much less readable for the annotated source. Furthermore rollup is practically purpose built for what we're doing.  It certainly has it's issues, but if we simplify the build we probably won't see them.

**But why remove the bundled build?** Is it just because it's too hard to build?  No. There have been arguments to remove it in the past: https://github.com/marionettejs/backbone.marionette/issues/2273

And I even attempted to remove it previously: https://github.com/marionettejs/backbone.marionette/pull/2485 (there's a lengthy argument about the bundled build's value there)

However! I can now argue additionally that we should "bundle" by default.  **This PR also pulls babysitter into the library.**  Babysitter is neglected. We build babysitter like logic into the `CollectionView` because it is abstracted and that causes issue after issue. (think filtering / sorting)  And it is one additional headache to deal with every time we make a release.. all babysitter is good for lately is updating its dependencies.

But wait doesn't that leave out Radio?  Yes, but the argument that we need to keep the bundled build was essentially that we wanted backbone users to be able to easily add one script and getting running.  You will be able to do this!  Radio is only a dependency of the Object's channel feature and isn't used internally.  So I added an error that is throw if that feature is attempted without the dependency.  Otherwise.. essentially core and bundled are the same.

Also resolves https://github.com/marionettejs/backbone.marionette/issues/3096

### CODE REVIEW

**Comment by JSteunou** [comment]
I'm all in! Did not except this to be dropped in this soon, but this is for the best I think.

My only concern is about how explain this change to the user, and the impact it could have. But for the sake of Marionette, this is all good!

Great job @paulfalgout :+1:

**Comment by ahumphreys87** [comment]
this looks good to me @paulfalgout

**Comment by denar90** [comment]
@paulfalgout what to do with `backbone.babysitter` repo, will we mark it as deprecated?

**Comment by paulfalgout** [comment]
I dunno what to do with babysitter..  I mean _someone_ could technically be using it directly...

**Comment by denar90** [comment]
Created some discussion issue https://github.com/marionettejs/backbone.babysitter/issues/78 about this.

**Pull request merged**
