### PR TITLE
Don't rerender the entire CompositeView on sorting

### PR DESCRIPTION
**Pull request by ahumphreys87**
Opening in favour of #2325 - rebased on minor branch

### CODE REVIEW

**Comment by samccone** [comment]
Sooooo can anyone come up with a case that this is breaking... I think it would break if someone was hooking into the render action for a compositeView or even onRender for the collectionView to set some attributes based on the sort order...

So it might be best to put this behind an option flag that will become the default in 3 :crying_cat_face:

**Comment by Dremora** [comment]
I've been very busy lately and didn't get a chance to finish #2325. I did however complete a test case (based on @ahumphreys87's code).
Documentation should still be updated.

```javascript
diff --git a/test/unit/composite-view.spec.js b/test/unit/composite-view.spec.js
index ab84cd4..431e5de 100644
--- a/test/unit/composite-view.spec.js
+++ b/test/unit/composite-view.spec.js
@@ -836,4 +836,35 @@ describe('composite view', function() {
       expect(this.constructor).to.have.been.calledOnce;
     });
   });
+
+  describe('when sorting a CompositeView without a childViewContainer', function() {
+    beforeEach(function() {
+      this.collection = new this.Collection();
+
+      this.ChildView = Backbone.Marionette.ItemView.extend({
+        tagName: 'span',
+        render: function() {
+          this.$el.html(this.model.get('foo'));
+        }
+      });
+
+      this.compositeView = new Marionette.CompositeView({
+        childView: this.ChildView,
+        collection: this.collection,
+        template: _.template('<p>Hello</p>')
+      });
+
+      this.compositeView.render();
+
+      this.collection.add(new Backbone.Model({foo: '1'}));
+      this.collection.add(new Backbone.Model({foo: '0'}));
+
+      this.collection.comparator = 'foo';
+      this.collection.sort();
+    });
+
+    it('should still render the markup of the template', function() {
+      expect(this.compositeView.$el).to.have.$text('Hello01');
+    });
+  });
 });
```

**Comment by ahumphreys87** [comment]
@samccone you make a good point, this is possible :(

Ill add a flag, what to call it: `onlyRenderChildrenOnSort`? :stuck_out_tongue:

**Comment by jasonLaster** [comment]
like it @ahumphreys87. also need a rebase

**Comment by jasonLaster** [comment]
Who cares if it's breaking. We're doing a major release.

**Comment by ahumphreys87** [comment]
closing in favour of #2457

**Pull request closed without merging**
