### PR TITLE
Deprecate multiple event handlers

### PR DESCRIPTION
**Pull request by paulfalgout**
Resolves https://github.com/marionettejs/backbone.marionette/issues/3503

### CODE REVIEW

**Comment by paulfalgout** [comment]
Maybe?  It's a bit sneaky maybe to do it so soon.. but I figured with a v3.5 release this is as early of a notification as possible regardless of if we remove it in v4.

**Comment by blikblum** [comment]
I think deprecating in 3.5 is enough to remove in v4.

**Comment by JSteunou** [comment]
:+1:

**Comment by paulfalgout** [comment]
@JSteunou are you approving this PR or just @blikblum 's comment?

**Comment by JSteunou** [comment]
Sorry, the comment

**Pull request merged**
