### PR TITLE
add docs for initial render requirement on CollectionView

### LINKED ISSUE #2016: "Initial" CollectionView render required in 2.2+?
Hi,

I wanted to upgrade Marionette, previously I was using version 2.1.0.
Now, in 2.2.2 (and 2.2.0) this issue occured, best explained with code:

```javascript
var employees      = new App.Collections.Employee();
var employees_list = new App.Views.EmployeeList({ collection: employees });

employees.reset(App.data.collection); // employees_list rendered automatically after this in 2.1.0

// after upgrade to 2.2.0 it does nothing until I add "initial" render:
employees_list.render();
```

Additionaly, Employee collection is PageableCollection and I use paginator. After first, initial render, the collection renders as it should after reset, but nothing happens if I ommit this first render.
Is this intended? From what I see in Marionette's code it is, but change log or docs don't mention it.

### PR DESCRIPTION
**Pull request by ahumphreys87**
Fixes #2016

### CODE REVIEW

**Comment by paulfalgout** [comment]
linter issue with spaces in the docs

**Comment by ahumphreys87** [comment]
:( should be fixed now

**Comment by jasonLaster** [comment]
:+1:

**Comment by ahumphreys87** [comment]
manually merged

**Pull request closed without merging**
