### PR TITLE
Remove unused listener from base view class.

### PR DESCRIPTION
**Pull request by samccone**
because good call @jmeas in #2133

### CODE REVIEW

**Comment by thejameskyle** [comment]
Hmm? https://github.com/marionettejs/backbone.marionette/blob/sjs/fix-unused-listener/src/collection-view.js#L116-L118

**Comment by samccone** [comment]
yeah it triggers show on all childviews when the parent is shown

**Comment by thejameskyle** [comment]
oooooh got it

:+1:

**Comment by paulfalgout** [comment]
Hmm I'd be up for renaming `onShowCalled` to something else.. not sure what.. `_onShow` `_proxyShowEvent` I dunno... at least `_onShowCalled`
Also `onShowCalled` should be removed from view https://github.com/marionettejs/backbone.marionette/blob/minor/src/view.js#L138

This is breaking, kind of, since it doesn't follow naming conventions..  I don't think this functionality is documented, but someone somewhere could be doing this:
```
var MyView = Marionette.ItemView.extend({
  onShow: function() {
    this.doSomething();
  },
  onShowCalled: function() {
    alert('Why God why?!?');
  }
});
```

**Comment by samccone** [comment]
yeah we say it is internal
https://github.com/marionettejs/backbone.marionette/blob/minor/src/view.js#L137

good catch... deleting

also @paulfalgout i am all for renaming the method

**Comment by paulfalgout** [comment]
Ah!  Ha.  Missed the inline comment :-)

**Comment by paulfalgout** [comment]
:+1:

**Comment by jmeas** [comment]
It should describe what it's doing, so I'm in favor with a name like `_propagateShowEvent`.

**Comment by jmeas** [comment]
Also, I could actually see regular old LayoutViews propagating this event to their children views, too. This will be of particular importance after #1263.

**Comment by samccone** [comment]
yeah i could see that also @jmeas this is mostly just a minor branch fixup

**Comment by jmeas** [comment]
:+1:

**Comment by thejameskyle** [comment]
:+1:

**Pull request merged**
