### PR TITLE
[WIP] filter should attach/detach and leave children alone

### PR DESCRIPTION
**Pull request by paulfalgout**
This is barely a WIP.. just some playing..

But while trying to wrap my head around the complexities in https://github.com/marionettejs/backbone.marionette/pull/3173 I began pondering what is making things so complex.

I think Marionette could support filter functionality in a very similar way / API as it does now, but if handled very differently it could greatly reduce the code complexity.  But there are so many moving parts I want to float the idea before I go any further..

**Proposal:**

Marionette's filtering should not modify `children`.  Filter should merely decide which children are attached / detached.  Marionette should maintain children as a collection of views that match the backbone collection.  If a view inside the children is not filtered out, it would be rendered and attached.. if that view is ever filtered out, it would merely be detached.. if the filter changed and it could be displayed again it would simply be reattached and not re-rendered.  Views that were never attached would never be rendered.

I believe this reduces the complexity greatly.  As models are added and removed from the collection, adding them to children is trivial as we don't have to worry about filtering..

So the logic would be
collection events -> update children -> sort children -> update DOM from sort -> attach/detach views as per the filter.

If a view is _removed_ from children via the bb model, then we'd destroy the childview.. otherwise we're just detaching until the collectionview is destroyed.. at that point we can clean up everything else.

### CODE REVIEW

**Comment by scott-w** [comment]
Have you looked into www.scottwalton.codes/marionette.collectionhelper which I wrote to be a way of handling sorting, filtering and paging separately from Mn views?

**Comment by paulfalgout** [comment]
I'm not against wrapping a collection for the purposes of sorting/filtering.  I'm not 100% sold on it needing to be apart of the API though.  I do think there's something to the views themselves handling this, but it is possible it is not reasonable... I don't like the current implementation.

But going back to the original issues for sorting and filtering, wrapping a collection was suggested:
https://github.com/marionettejs/backbone.marionette/issues/2056
https://github.com/marionettejs/backbone.marionette/issues/1596

I do wonder, if done correctly, if handling sorting / filtering at the view level can produce more performant collections.  But I don't know what the solution is.

However as @samccone mentions the filter functionality was meant to be "presentation only" https://github.com/marionettejs/backbone.marionette/issues/1596#issuecomment-48414718
I think attaching/detaching accomplishes this better and is far less of an issue than the current implementation..

Really though we need some good perf testing to understand the best direction.

But I'm not quite ready to dump everything and start over.  If a solution can be done with clean code and good performance using the same API, that'd be my preference.

**Comment by scott-w** [comment]
How would you see this interacting with, say `Backbone.Paginator` and other helper utilities that hide the fact that there's a full collection of which the `CollectionView` only renders some?

**Comment by paulfalgout** [comment]
@scott-w I really don't..  I think filter is better in a collectionview if it is presentation only as it was initially suggested..   I don't think collectionView should be messing with or needing to know much about the data aspect of it.. I think that is over-reaching and poorly located.. if that is the need.. you should filter the collection _prior_ to sending it to the collectionView, much like your library.  I think filter on the collection should be a very easy, very performant way of hiding and showing stuff that's in the collection.. and it should do very little else.

**Comment by JSteunou** [comment]
I'm in favor of the initial suggestion, I did it that way before filtering was in Marionette, and indeed it is easier to maintain

**Comment by paulfalgout** [comment]
@JSteunou sorry clarify please.. what is the initial suggestion?

**Comment by JSteunou** [comment]
maintaining all children in the view and only play with detach / attach

**Comment by paulfalgout** [comment]
closing in favor of https://github.com/marionettejs/backbone.marionette/pull/3244

**Pull request closed without merging**
