### PR TITLE
Fix region.empty({preventDestroy: false}) bug.

### LINKED ISSUE #2611: Region.empty fails to destroy view when called with any options
In Marionette 2.4.2, calling `region.empty` with any options prevents the contained view from being destroyed. Here is an example:

```
var region = new Marionette.Region({el: $('<div>')});
var view = new Marionette.ItemView({template: false});
region.show(view);
region.empty({});
console.log(view.isDestroyed); // Logs false
```

Calling `region.empty()` without any arguments results in the view being destroyed as expected. The bug seems to be due to the fact that the `empty` function uses `Marionette._getValue` incorrectly to find the value of preventDestroy that is passed into the function:

```
var preventDestroy = Marionette._getValue(options, 'preventDestroy', this);
```

When the line above runs, `preventDestroy` gets set to the value of `options` (`{}` in my example) instead of the value of `options.preventDestroy`.

### PR DESCRIPTION
**Pull request by bradlord**
Fixes #2611.

I wasn't sure which branch to request this to be merged into. CONTRIBUTING.md suggests making changes to the minor branch, but that doesn't seem to have been updated recently. I originally requested (#2612) that this be merged into the 2.4.2 branch, but after looking more closely, I realized that didn't make much sense.

### CODE REVIEW

**Comment by jasonLaster** [comment]
sorry for the confusion @bradlord. @ianmstew thoughts?

**Comment by samccone** [comment]
@bradlord can you add the test case initially outlined in your origin issue please?

**Comment by ianmstew** [comment]
@bradlord We have the correct patch branch sorted out.  Move this to the new `2.4.3` branch and we will move forward with merging.  That should be seamless for you since `master` and `2.4.2` have the same HEAD at this moment.

**Comment by ianmstew** [comment]
Update: PR against `patch` instead.  This should still be seamless.

**Comment by bradlord** [comment]
I created a new PR (#2631) against `patch`.

**Pull request closed without merging**
