### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by denar90**
Changes due to [discussion](https://github.com/marionettejs/marionettejs.com/pull/451)

### CODE REVIEW

**Comment by scott-w** [comment]
Can you whack a heading of `### Index Ordering` in then I'll be happy to 👍 this

**Comment by denar90** [comment]
Thanks for comment, already added changes.

**Comment by scott-w** [comment]
Awesome, I'll give my :+1: now

**Comment by denar90** [comment]
thanks 😄

**Pull request merged**
