### PR TITLE
onBeforeAttach and onAttach for CollectionView child views

### LINKED ISSUE #2526: Trigger onAttach on child views during CollectionView re-render
After a CollectionView has been shown into a Region, re-rendering the CollectionView does not trigger onAttach/onBeforeAttach on its child views, and similarly when adding new child views.

Back port of #2209 for 2.4.2.

### PR DESCRIPTION
**Pull request by ianmstew**
Fixes #2526.  Cherry-pick of #2481 for 2.4.2.

### CODE REVIEW

**Comment by ianmstew** [comment]
Pinging @ahumphreys87 and @jasonLaster--you guys thumbs-upped the original PR against `next`.  :)

**Comment by ianmstew** [comment]
The main difference between this and the original PR is that, instead of calling `Marionette.triggerMethodMany()`, I'm calling `this._triggerMethodMany()`, which is actually Jason's code from `next` that I dropped into CollectionView for backward-compatibility.

The second difference is the `once('render'` approach to firing `before:show` within `_addChildView()` that we agreed on strictly for 2.4.2 here: https://github.com/marionettejs/backbone.marionette/pull/2481#issuecomment-92442727.

**Comment by jasonLaster** [comment]
Is it safe to drop addEmptyView? Sorry Ian if yhis is more work.

**Comment by ahumphreys87** [comment]
That's my only questions also, tricky as its one of those methods that probably should never have been "public" as it does so much that people shouldn't mess with but because it was it will be a breaking change :(

**Comment by ianmstew** [comment]
Ahh, I overlooked that.  No problem at all.

**Comment by ianmstew** [comment]
There we go.  I wanted to cry bumping `maxstatements` and `maxcomplexity` just because of `addEmptyView()`...

**Comment by ahumphreys87** [comment]
yeah it's ok we can kill it in 3.0 :)

:+1:

**Comment by jasonLaster** [comment]
:boom:

**Pull request merged**
