### PR TITLE
Behaviors as constructor opts

### PR DESCRIPTION
**Pull request by adorsk**
New PR based on discussion in  #2537.

PR for #2386.

Additional specs added to test/unit/behaviors.spec.js .

### CODE REVIEW

**Comment by ahumphreys87** [comment]
this lgtm, @jasonLaster @paulfalgout could you give this the once over?

**Comment by jasonLaster** [comment]
Yup legit. Good example of how code became simpler/idiomatic. I love seeing logic leave the behaviors function.

**Comment by paulfalgout** [comment]
:+1: just needs a squash

**Comment by ahumphreys87** [comment]
cherry picked onto `next`

thanks @adorsk

**Comment by adorsk** [comment]
:)

**Pull request closed without merging**
