### PR TITLE
Override behavior ui with view ui

### PR DESCRIPTION
**Pull request by stephanebachelier**
See description in #2266

### CODE REVIEW

**Comment by samccone** [comment]
@stephanebachelier mind opening this into major and we can talk about it there?

**Comment by jasonLaster** [comment]
Yup. Major cause it's breaking

**Comment by stephanebachelier** [comment]
@samccone @jasonLaster ok. does you need something else ?

**Comment by stephanebachelier** [comment]
superseeded by #2308

**Pull request closed without merging**
