### PR TITLE
Bump and build v3.0.0-pre.4

### PR DESCRIPTION
**Pull request by ahumphreys87**

### CODE REVIEW

**Comment by scott-w** [comment]
IIRC we've also got a basic upgrade guide there too.

**Comment by denar90** [comment]
This is definitely :+1:

**Comment by ahumphreys87** [comment]
@scott-w added upgrade guide to changelog

**Comment by JSteunou** [comment]
@scott-w should be mentioned in the changelog?

**Comment by JSteunou** [comment]
@ahumphreys87 was faster 

it's a :+1:

**Pull request merged**
