### PR TITLE
throw error when region has more than one element

### PR DESCRIPTION
**Pull request by erikahlswede**
### Proposed changes
 - Throw an error if a region has more than one element

Link to the issue:
#3320

I played around with a warning mechanism...but at the end of the day, it was `console.warn`.  I like the idea of throwing an error in this situation.  This way, it is much more clear to the user, rather than having views show up in the wrong spots ☹️

### CODE REVIEW

**Comment by paulfalgout** [comment]
@marionettejs/marionette-core feeling on whether or not this should be considered breaking?

**Comment by erikahlswede** [comment]
When writing this, I figured it would be considered breaking. There may be cases where multiple elements are found for a region and the app functions perfectly fine (happen to be the first element in the list).

**Comment by rafde** [comment]
@paulfalgout It's definitely a major and breaking change. This is best something for Mn 4.

**Comment by scott-w** [comment]
I agree, this is a breaking change. While a developer _shouldn't_ add regions where selectors will hit multiple nodes, the fact is that they _can_ and, thus, probably have.

I'd happy :+1: this for Mn 4 as I think it's the right way to go.

**Comment by JSteunou** [comment]
@erikahlswede could you rebase your branch ?

**Comment by paulfalgout** [comment]
FWIW I'm no longer certain this should go in v4.  I think perhaps Region has some problems that could be resolved better than an error.

**Comment by paulfalgout** [comment]
I think in the end the solution will be handled differently.  Too many caveats in the error.

**Pull request closed without merging**
