### PR TITLE
Simplify Travis Matrix

### LINKED ISSUE #2609: Simplify travis-ci testing matrix
We should remove node 0.11.
Testing should likely be done mostly on 0.12 with a few on 0.10 and on io.js

Example:
https://github.com/marionettejs/backbone-metal/blob/master/.travis.yml#L7

### PR DESCRIPTION
**Pull request by megawac**
Fixes #2609 

There doesn't seem to be any reason to run travis on multiple versions of node as `Marionette` runs primarily on the browser. Currently we're running **36** different travis VMs per commit. This brings it down to **12**.

### CODE REVIEW

**Comment by megawac** [comment]
/cc @ahumphreys87

If we want to test multiple versions of node we can change the matrix on a per test level (I think we do that in Radio)

**Comment by jasonLaster** [comment]
yea, totally agree. It'll speed stuff up for sure

**Comment by samccone** [comment]
lets keep node 10 around plz enough people are still on it, that makes it important to ensure those people can contribute to the source

**Comment by paulfalgout** [comment]
Yep I think the reason to try node 10.. or _maybe_ io is specifically for dev environments.  For a while 0.12 wasn't working for us at all.. which I think is why the matrix was changed to begin with, but we don't need to test everything with all 3..  just 1

**Comment by megawac** [comment]
In that case, do you prefer this?

**Comment by megawac** [comment]
There we go, fixed it

**Comment by samccone** [comment]
:+1:

**Comment by paulfalgout** [comment]
:+1:

**Pull request merged**
