### PR TITLE
Test lodash

### PR DESCRIPTION
**Pull request by paulfalgout**
Note that this includes: https://github.com/marionettejs/backbone.marionette/pull/3292
I didn't want to introduce a slower CI or cause merge issues.

This adds the ability to test underscore and/or lodash.  It also would allow us to reinstate a test matrix.. though I don't know that we need to do that at the moment.

Resolves https://github.com/marionettejs/backbone.marionette/issues/2940

Testing that this actually works was moderately simple.  If you remove `_.invokeMap ||` from https://github.com/marionettejs/backbone.marionette/blob/master/src/utils/invoke.js#L5 then `yarn run test` still works, but `yarn run test-lodash` lights up big time.

### CODE REVIEW

**Comment by blikblum** [comment]
Good work. Has my 👍

**Comment by denar90** [comment]
@paulfalgout do you want to merge this one into `next` instead of `master` ?

**Comment by paulfalgout** [comment]
Well I figured at the moment `next` is getting all of the code changes so we don't really need this on master, but we do need it on `next`.  I suppose we could put it on master and then pull it over, but to me at this point it seems like it would be fine either way as long as `next` gets it.

**Comment by denar90** [comment]
Got it. Merging this. We will just have to pull master into next, to solve possible merge conflicts asap.

**Comment by paulfalgout** [comment]
Ah so the 1st commit is the commit that went into master.. I just cherry-picked it here.. so there shouldn't be any merge conflicts.

**Pull request merged**
