### PR TITLE
[docs-fix] showChildView

### PR DESCRIPTION
**Pull request by tsm91**
As mentioned in http://marionettejs.com/docs/v2.4.4/marionette.layoutview.html#basic-usage reference a region with the `showChildView` method.

### CODE REVIEW

**Comment by paulfalgout** [comment]
:+1:

**Comment by paulfalgout** [comment]
Thanks!

**Comment by tsm91** [comment]
yw, one thing to note. On http://marionettejs.com/docs/v2.4.4/marionette.view.html the docs is still the same. I see there is a `compile docs` grunt task in the website's repo that i assume would update http://marionettejs.com/docs/ from this repo's docs folder.

Some kind of git post-merge hook should be introduced here i think. For Example if the title contains [docs-fix] you could run a shell script that goes to website repo, run grunt compile docs and push to remote.

**Comment by paulfalgout** [comment]
I was pretty sure the site rebuilds anytime something is pushed to master..  But I assume the docs are specific to the release tag.
@samccone maybe we need to add an additional @latest or something to the docs that is whatever is on master.  hrmmmm

**Pull request merged**
