### PR TITLE
Introduce view.getUI

### LINKED ISSUE #2102: Introduce `getUi`
View's `ui` hash stands out among the properties that Marionette introduces, and not in a good way. Unlike most (all?) other attributes, we modify the `ui` hash *directly* once the view has been rendered. Consequently, if you access `view.ui.myElement` before rendering, you get a string, and after rendering you get a jQuery object.

It would be much better, I think, if we left `this.ui` alone. It would *always* be strings. To access the ui elements, we would introduce a new API method: `getUi`.

```js
view.getUi('myElement');
```

If you call this before the view has been rendered, we throw a Marionette Error telling you to render it first. And if you call it after the view has been rendered, you get your jQuery object.

While we can't change `this.ui.x` until the next major release, we can introduce this new API method and encourage using it over the old means of accessing ui.

Thoughts?

### PR DESCRIPTION
**Pull request by duncanbeevers**
getUI is a stable interface to the view ui hash

An error is thrown when attempting to access undefined ui elements.
An error is thrown when attempting to access ui elements before the view has been rendered.
The jQuery collection matching the ui element selector is returned when the view is live.
An empty jQuery collection is returned after the view has been destroyed.

Fixes #2102

### CODE REVIEW

**Comment by jasonLaster** [comment]
Lets get this figured out :)

https://gist.github.com/jasonLaster/2d9ff5b691b84a77e0eb

```diff
diff --git a/htdocs/assets/js/seller-platform/modules/ListingManager/modules/Edit/views/form/Tags.js b/htdocs/assets/js/seller-platform/modules/ListingManager/modules/Edit/views/form/Tags.js
index 917fc9d..bb53633 100644
--- a/htdocs/assets/js/seller-platform/modules/ListingManager/modules/Edit/views/form/Tags.js
+++ b/htdocs/assets/js/seller-platform/modules/ListingManager/modules/Edit/views/form/Tags.js
@@ -139,6 +139,12 @@ define([
 
         onCollectionChange: _.debounce(function() {
             this.model.set(this.modelField, this.collection.pluck('value'));
+
+            // SE-2438 - SE-2439 : Because this method is debounced, it's possible for it
+            // to get called *after* the view has been destroyed
+            if (!_.isObject(this.ui.input)) {
+                return;
+            }
             if (this.isFull()) {
                 this.disableInput();
             } else {
```

**Comment by thejameskyle** [comment]
Still a no for me, I want to kill `this.ui` in v4 anyways for reasons I outlined elsewhere.

**Comment by jasonLaster** [comment]
@duncanbeevers mind doing a rebase off of minor. We recently did a release and this got out of sync.

@thejameskyle - I just re-read the [PR](https://github.com/duncanbeevers/backbone.marionette/commit/10e2d779b0ddb2fd2f0ff2e58568bec0a896d56a) and `getUI` is very low impact. I think it will help a lot of people in 2.x and 3.x who would like to use `ui` with guarantees that they're interacting w/ a jQuery bug. 

---

@marionettejs/marionette-core mind weighing in? It'd be good to have some resolution here.

**Comment by ahumphreys87** [comment]
I'm :+1: on this change, I'd much rather give users an error message that helps them debug, much in the same way we do in  `_ensureViewIsIntact`.

I'd like to see some doc changes around `this.ui` to encourage the use of `getUI` though, we need to make people aware that this is what they should be using otherwise they will still be exposed to the issue.

**Comment by samccone** [comment]
yep I am :+1: on it still 

>  I'd much rather give users an error message that helps them debug, much in the same way we do in _ensureViewIsIntact.

kk lets get this sucker rebased and get it in for the smaller 2.5 release :floppy_disk:

**Comment by ahumphreys87** [comment]
Closing in favour of rebased PR #2399 

thanks for the work @duncanbeevers

**Pull request closed without merging**
