### PR TITLE
Remove _.bindAll usage

### PR DESCRIPTION
**Pull request by megawac**
#2689

### CODE REVIEW

**Comment by jasonLaster** [comment]
lol, so reasonable. why patch and not `next`? not that it really matters

**Comment by megawac** [comment]
It's not a breaking change, figured it may as well go into patch

**Comment by paulfalgout** [comment]
Related https://github.com/marionettejs/backbone.marionette/issues/2372

**Comment by paulfalgout** [comment]
:+1: @ianmstew @jasonLaster this is a quick one.  Really no change here.  Travis failing is only the `io.js` issue.

**Pull request merged**
