### PR TITLE
WIP Reimagining Region

### PR DESCRIPTION
**Pull request by paulfalgout**
This is a breaking WIP.. And it is a long way out.. just wanted to start the conversation.

Essentially the main idea will be to reduce the region API a lot.  Much of that is possible by changes to the region mixin..

The next steps possibly will be to modify the region mixin so that regions are instantiated with an `el` at the moment `getRegion` is used instead of at view instantiation.  Then instead of resetting regions we can destroy and re-instantiate them on render.  

And further we'll possibly be able to detach the views within the regions.. we can attempt to recreate known regions after render and reattach views.

This would also allow for further abstraction of regions where we could allow for `this.showChildView(this.ui.someRegion, myView);` or even `this.showChildView('.some-selector', myView);`

### CODE REVIEW

**Comment by rafde** [comment]
[Regionifying CollectionView](https://github.com/marionettejs/backbone.marionette/issues/2560) not part of this? I am seeing more implicit region related issues with using regions as a way to append to rather than remove.

It seems like people (maybe) want to do, aside from showChildView, is a setChildView('region', view')
where the contents are kept but the region is used as the view's `el`.
The issue with this is: How does empty work?

> This would also allow for further abstraction of regions where we could allow for this.showChildView(this.ui.someRegion, myView); or even this.showChildView('.some-selector', myView);
 
I think we can do this now if we allow `showChildView` to check `regions` has first, then the hash value if it's defined, otherwise assume it's a selector/DOM/jQuery

but the issue with that is: how do I get the a region's view?

**Comment by paulfalgout** [comment]
> where the contents are kept but the region is used as the view's el.

I think that is just `showChildView('region', myView, { replaceElement: true });` ?

**Comment by rafde** [comment]
replaceChild is a https://github.com/marionettejs/backbone.marionette/blob/master/src/region.js#L184
So the region's el gets replaced by the view's el
set is more like

```js
new View({
  el: this.getRegion('region').el
});
```
Which is similar to how I (maybe?) solved for https://github.com/marionettejs/backbone.marionette/issues/3150#issuecomment-243952941

**Comment by paulfalgout** [comment]
I guess I just don't know why you'd want to set the region's el as the view's el.  It seems backwards if it is the life-cycle container.  I think it's still just `replaceElement` where the region and view are init'd with the same `el`.  If you want to attach pre-existing DOM to a view I'd think you'd do it like this:

```
MyView.extend({
  ui: {
    foo: '.some-selector'
  },
  regions: {
    region: '@ui.foo'
  },
  onRender(){
    const myChild = new Mn.View({ el: this.ui.foo });
    this.showChildView('region', myChild, {replaceElement: true}); 
  }
});
```

**Comment by rafde** [comment]
The way I defined it preserves the contents. example
```html
<table data-ui="table">
  <thead>
    <!-- don't remove me, bro -->
  </thead>
  <!-- collection will be appended here -->
</table>
```
```js
new CollectionView({
  collection,
  el: this.ui.table[0],
  childView: TBodyView
});
```

this allowed for the thead to be kept while being able render the models with `tbody` as the `tagName`.

**Comment by paulfalgout** [comment]
At that point, what is the purpose of having the region in that at all?

**Comment by rafde** [comment]
Like the Region class binding to the DOM? Nothing, now that you point that out. I always saw regions as place holders for rending *View classes. What I didn't like was all the wrapping that came with showChildView, and in some cases I use the example I gave.

**Comment by paulfalgout** [comment]
I think a Region's main goal is handling the lifecycle events.  I think that once you want some DOM and a view inside a "region" you now have a CollectionView.

What I don't want to start supporting with a single region is:
```html
<table data-ui="table">
  <!-- a view get's appended here -->
  <thead>
    <!-- don't remove me, bro -->
  </thead>
  <!-- a different view get's appended here -->
  <!-- a completely different view get's appended here -->
</table>
```

or even just
```html
<table data-ui="table">
  <!-- a view get's appended here -->
  <thead>
    <!-- don't remove me, bro -->
  </thead>
</table>
```

**Comment by rafde** [comment]
yeah, that looks like a massive nightmare to support. Also, fragile. All thought provoking ideas, is all.

**Comment by paulfalgout** [comment]
Closing this for now.  This PR did it's job mostly.. will reinvestigate when other things start to shake out.

**Pull request closed without merging**
