### PR TITLE
2.4.2

### PR DESCRIPTION
**Pull request by ahumphreys87**

### CODE REVIEW

**Comment by ahumphreys87** [comment]
@marionettejs/marionette-core can I get some :eyes:

**Comment by paulfalgout** [comment]
LGTM :+1:  Ran a sanity check against my app and in IE8.  No apparent issues.

**Comment by JSteunou** [comment]
any news one this release?

**Comment by samccone** [comment]
just waiting on some responses from people :)

I may just cherrypick e787839 to get the bug fix out the door and we can work on getting the rest of the fixes in

**Comment by ahumphreys87** [comment]
@ping @jasonLaster @ianmstew you guys free to answer @samccone 's questions?

**Comment by jasonLaster** [comment]
Left some comments. I say we do one deploy soonish.

**Comment by paulfalgout** [comment]
Is this missing https://github.com/marionettejs/backbone.marionette/pull/2384

**Comment by JSteunou** [comment]
seems so

**Comment by ahumphreys87** [comment]
@paulfalgout added #2384

**Comment by ahumphreys87** [comment]
ok ive added `b6a7df9`.

waiting on #2561 and will build libs again

**Comment by ahumphreys87** [comment]
@samccone now that the dep bump is merged im gonna create a new 2.4.2 branch. what do we want in it?

I'd say at least:

@e787839
@f9c7358
@75e7cab

and the dep bump.

Thoughts?

**Comment by samccone** [comment]
:+1:

**Comment by paulfalgout** [comment]
:+1:

**Pull request merged**
