### PR TITLE
add docs for re-rendering on sort

### LINKED ISSUE #2247: Documentation: CollectionView / CompositeView sort rerender
At present, the CollectionView and CompositeView documentation speaks to the view re-rendering on a collection 'reset' event, but does not speak to it re-rendering on a 'sort' event.  In that the views do re-render on 'sort', it would be helpful to document this.

Additionally, given the relative functions of these two classes, it should be made clear that CompositeView completely re-renders on sort, rather than just re-rendering the child view container.

While completely re-rendering in CollectionView is obvious, I think that it's less so in CompositeView, and so it'd not be unexpected that only the CompositeView's childViewContainer would be re-rendered, when in fact the opposite is true.

### PR DESCRIPTION
**Pull request by ahumphreys87**
Fixes #2247

### CODE REVIEW

**Comment by ianmstew** [comment]
Should we address the concern from #2247 that re-rendering not just the childViewContainer but also the entire compositeView is re-rendered without `reorderOnSort`?

**Comment by ahumphreys87** [comment]
I debated that but we have changed this for v3 with this PR: https://github.com/marionettejs/backbone.marionette/pull/2467 when we cherry pick onto 2.4.2 we should add a warning or something for CompositeView

**Comment by ianmstew** [comment]
Ahh, very nice!

**Comment by ianmstew** [comment]
:+1:

**Pull request merged**
