### PR TITLE
Remove component.json

### PR DESCRIPTION
**Pull request by cmisenas**
Fixes https://github.com/marionettejs/backbone.marionette/issues/2601

### CODE REVIEW

**Comment by pascalpp** [comment]
Does marionette also need to be 'unpublished' from component?

**Comment by cmisenas** [comment]
Good question. Looks like they use a [wiki page](https://github.com/componentjs/component/wiki/Components)

**Comment by samccone** [comment]
I think doing this would be a breaking change right?

**Comment by pascalpp** [comment]
No match for marionette on http://component.github.io. So maybe it was never published to component?

**Comment by cmisenas** [comment]
@pascalpp It is on the old registry (their wiki page) which I believe is still being used cause I can run `component install marionette` successfully. 

@samccone yes. From my understanding though reading #2601 is that not many people are using it nowadays.

**Comment by ahumphreys87** [comment]
yup this would be breaking, its going into `next` though so that's fine - we just dont push till 3.0.

:+1:

**Comment by jasonLaster** [comment]
Merged. Thanks @cmisenas! We can always re-add if this registry takes off

**Pull request merged**
