### PR TITLE
Bump and build v3.0.0-pre.5

### PR DESCRIPTION
**Pull request by ahumphreys87**

### CODE REVIEW

**Comment by rafde** [comment]
nice. I guess I best prep my https://github.com/marionettejs/backbone.marionette/compare/next...rafde:collectionview-update-remove branch.

**Comment by paulfalgout** [comment]
Can you remove the `/lib/core/`  I think these are from the last build

**Comment by ahumphreys87** [comment]
@rafde are these changes breaking? Is there an open issue that gives the reasons for the PR?

Wondering if we need this in v3 or if it can go in a 3.x

**Comment by paulfalgout** [comment]
👍 🎉

**Pull request merged**
