### PR TITLE
Remove Marionette.Module doc for v3

### PR DESCRIPTION
**Pull request by andrewmnlv**

### CODE REVIEW

**Comment by scott-w** [comment]
Hi @andrewmnlv Thanks for this. For the initial v3 release, I'd rather use a deprecation notice at the top to prepare readers for the removal of the feature.

**Comment by andrewmnlv** [comment]
Hi @scott-w 
It was deprecated on v2.4.2  And may be better remove module doc totally as for controllers?)

**Comment by scott-w** [comment]
The only issue I have is we've had no big *Deprecated* notice at the top. I'd be 100% behind removing all text in favour of just a deprecation/removed notice that would lead to the file being deleted in 3.1.

That way we can point people at proper module loaders from that documentation e.g. Webpack/Browserify

**Comment by scott-w** [comment]
I've been discussing this and I've started to come round to your way of thinking, so I'll 👍 this

**Comment by andrewmnlv** [comment]
@scott-w thanks :+1:

**Pull request merged**
