### PR TITLE
Add examples for Mn.Object

### PR DESCRIPTION
**Pull request by denar90**
### Proposed changes
 - added examples for `Mn.Object`
 - replaced fiddle by Mn account
 - updated doc for `Mn.Object`

Link to the issue:
related #3012 #3133

### CODE REVIEW

**Comment by ahumphreys87** [comment]
👍

**Comment by denar90** [comment]
Also added examples to Radio doc. Think it's a bit related.

**Comment by ahumphreys87** [comment]
👍 again :)

**Comment by denar90** [comment]
fix conflicts

**Pull request merged**
