### PR TITLE
Fix tests in CI (wip)

### PR DESCRIPTION
**Pull request by denar90**
Fix issue with broken build tests. In travis we have error.
`Error: jQuery requires a window with a document`

### CODE REVIEW

**Comment by paulfalgout** [comment]
This is a dependency that broke on a patch update that was release in the last 3-5 days.  My guess is jsdom's patch release..  I'd try just putting everything back and removing all the `^`s from the devDeps.

**Comment by denar90** [comment]
@paulfalgout 👍 
I tried just downgrade `mocha` and `jsdom` versions. Didn't help...
By the way, local tests after clean `npm i` passed fine. Strange...

Closing this pr since I didn't find solution 😞

**Comment by paulfalgout** [comment]
Possibly a difference in node versions?

**Comment by denar90** [comment]
can be, my is v6.

**Pull request closed without merging**
