### PR TITLE
Coerce isDestroyed()/isRendered to boolean

### LINKED ISSUE #2756: isDestroyed()/isRendered should coerce boolean
https://github.com/marionettejs/backbone.marionette/commit/e8dd1e5dda1590a056204c912d593be09cffc8c5#commitcomment-13327142

### PR DESCRIPTION
**Pull request by paulfalgout**
Resolves #2756

### CODE REVIEW

**Comment by paulfalgout** [comment]
meh there's a `_isDestroyed` test failing.  If everyone's ok with removing them from the prototype, I'll update the test.

**Comment by megawac** [comment]
= on this as its private, but I prefer the flag to be explicitly set rather than undefined at init

**Comment by paulfalgout** [comment]
Cool.. I don't really have a strong opinion either way.  I put them back.

This should be an easy :thumb: and merge @marionettejs/marionette-core

**Comment by ahumphreys87** [comment]
:+1:

**Comment by jasonLaster** [comment]
:+1:

**Pull request merged**
