### PR TITLE
LayoutView should remove its element before destroying child regions

### LINKED ISSUE #2134: Update layoutView destroy mode
LayoutViews [destroy their regions before destroying themselves](https://github.com/marionettejs/backbone.marionette/blob/master/src/marionette.layoutview.js#L48-L49). This creates `n` DOM paints, one for each layer of views.

Imagine a three-level nested LayoutView tree. The tree is attached to the document. You call destroy on the parent view, which calls destroy on its RegionManager before it, itself, is destroyed. That destroy call will remove the children separately from the parent.

LayoutView needs a custom destroy for efficiency.

### PR DESCRIPTION
**Pull request by megawac**
Resolves #2134, the layout views element should be removed before destroying the child regions and views

### CODE REVIEW

**Comment by samccone** [comment]
@megawac mind rebasing off of major

**Comment by jasonLaster** [comment]
That or a feature flag.

**Comment by samccone** [comment]
so based on the view talks that we have had does this still have a place? Is this something we want to be messing with for the next release?

**Comment by samccone** [comment]
yes it is

**Comment by megawac** [comment]
:wolf:

**Comment by samccone** [comment]
1 commit, and some docs and then :ship:

**Comment by jasonLaster** [comment]
:+1: Lets get this in

**Comment by samccone** [comment]
we just need to add docs to the layoutView md file

**Pull request merged**
