### PR TITLE
CollectionView#reorder will remove an already displayed emptyView

### PR DESCRIPTION
**Pull request by paulfalgout**
This regression was introduced in `2.4.4`

### CODE REVIEW

**Comment by JSteunou** [comment]
For historic and comparison, which commit introduced the regression ?

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/backbone.marionette/commit/0d913a524a71a9b4427256b0ba1b3236abeee9d6#diff-091acc5f607e2622bd6cabf705443fffR186

This line check's the view's children which can be the `emptyView` and later removes it.  But it doesn't unset the `_showingEmptyView` so `checkEmpty` does nothing.

**Comment by JSteunou** [comment]
nice catch, tricky one!

**Comment by ahumphreys87** [comment]
👍

**Pull request merged**
