### PR TITLE
Accept ChildView as a function and make getChildView private (issue #184...

### PR DESCRIPTION
**Pull request by ahumphreys87**
...6)

Conflicts:
	docs/marionette.collectionview.md
	src/collection-view.js

### CODE REVIEW

**Comment by ahumphreys87** [comment]
ping @marionettejs/marionette-core moving from #2420 and merging into next

**Comment by jasonLaster** [comment]
looks like coverage is missing this line: https://coveralls.io/files/602916446#L58

**Comment by ahumphreys87** [comment]
Maaan ill take a look

**Comment by jasonLaster** [comment]
Nice, @ahumphreys87. @marionettejs/marionette-core :eyes: please

**Comment by ahumphreys87** [comment]
hahahah - damn you coveralls!!

**Comment by jasonLaster** [comment]
Haha.

**Comment by jasonLaster** [comment]
:+1: 

@marionettejs/marionette-core needs a thumb

**Comment by paulfalgout** [comment]
:+1:

**Comment by paulfalgout** [comment]
Well.. this was passing, but not with the next merges..  :sob:

**Pull request merged**
