### PR TITLE
Merge LayoutView into ItemView.

### PR DESCRIPTION
**Pull request by ahumphreys87**
Cherry pick from major - 2 conflicts. Both really simple merges but thought best to PR to get eyes before pushing into next.

ping @marionettejs/marionette-core 

Resolves #2253

Conflicts:
	src/layout-view.js
	test/unit/item-view.child-views.spec.js

### CODE REVIEW

**Comment by ahumphreys87** [comment]
guess its lucky I did PR, tests failing now. Maybe not such a simple merge hehe

**Comment by ahumphreys87** [comment]
@marionettejs/marionette-core tests should be fixed. Needed to merge in `childEvents` from layoutView into abstractView so needs :eyes:

**Comment by ahumphreys87** [comment]
also be worth a double check incase any other changes to LayoutView need brought into ItemView now

**Comment by jasonLaster** [comment]
> Last of the bigies

**Pull request merged**
