### PR TITLE
Deprecate Marionette.Module

### LINKED ISSUE #2403: Deprecate Modules
So https://github.com/marionettejs/marionette.module states that Modules have been deprecated.

The callback / initializer portion of modules have been deprecated in the docs, but otherwise this has yet to be officially deprecated.

### PR DESCRIPTION
**Pull request by paulfalgout**
And link to the shim
Resolves #2403

### CODE REVIEW

**Comment by jasonLaster** [comment]
:+1:

**Comment by jasonLaster** [comment]
lol, travis is so confused

**Comment by cmaher** [comment]
that collection-view.spec thing is maddening

**Comment by jasonLaster** [comment]
haha

**Comment by paulfalgout** [comment]
Yeah travis is already messed up from a prior commit.. probably a merge issue with the jscs stuff.. I think we've probably fixed this same issue 5 times now on various branches.. do we want to fix it here as well?

**Comment by paulfalgout** [comment]
Found the fix in `next` and cherry-picked

**Comment by jasonLaster** [comment]
Can we get one more thumb for the deprecate message

**Comment by ahumphreys87** [comment]
:+1:

**Pull request merged**
