### PR TITLE
CollectionView viewComparator option for custom collection view sorting

### PR DESCRIPTION
**Pull request by cpjolicoeur**
See discussion here: https://github.com/marionettejs/backbone.marionette/issues/2056

### CODE REVIEW

**Comment by samccone** [comment]
@cpjolicoeur would you mind rebasing so i can throw this sucker into 2.4 

thansk sorry for the delay

**Comment by cpjolicoeur** [comment]
@samccone rebased :gem:

**Comment by samccone** [comment]
thanks

**Comment by samccone** [comment]
:ship:

**Pull request closed without merging**
