### PR TITLE
Remove redundant return statement

### PR DESCRIPTION
**Pull request by natalan**
Remove redundant `return` in region's `show` method.

### CODE REVIEW

**Comment by jasonLaster** [comment]
congratulations making it to the end of the `show` method :)
seriously, nice catch. 

---
+ just rebooted the failed test
+ do we want to merge onto master or `next`. Generally we don't put new src code into master w/ the policy that head should be identitcal to the last release.

**Comment by paulfalgout** [comment]
I'd vote `next`  Could certainly cherry pick it if there is another patch for v2.4

**Comment by ahumphreys87** [comment]
:+1: for `next`

**Comment by ahumphreys87** [comment]
cherrypicked onto next

**Comment by ahumphreys87** [comment]
nice spot @natalan

**Pull request closed without merging**
