### PR TITLE
custom renderer - issue #2474

### PR DESCRIPTION
**Pull request by paulovieira**
This pull request makes a small change to `_renderTemplate` which allows the user to define a custom renderer. Please see issue #2474 for more details about the main objective.

A concrete example of this new feature (using the [Nunjucks](http://mozilla.github.io/nunjucks/) templating engine with pre-compiled templates) is below:
```js
var MyView = Mn.View.extend({

    template: "something/templates/hello-world.html",

    renderer: function(template, data) {

        if (!template) {
            throw new Marionette.Error({
                name: 'TemplateNotFoundError',
                message: 'Cannot render the template since its false, null or undefined.'
            });
        }

        var output = "";
        try {
            // nunjucks will look for the pre-compiled template at window.nunjucksPrecompiled;
            // more details here: https://mozilla.github.io/nunjucks/api.html#browser-usage
            output = nunjucks.render(template, data);
            return output;
        } catch (err) {
            throw new Marionette.Error({
                name: 'NunjucksError',
                message: err.message
            });
        }
    }
});
```

This example shows a custom renderer for a specific view. However the default renderer (Mn.Renderer.render) could also be easily overridden by defining the custom renderer at `Backbone.View.prototype.renderer`.

By the way, people are doing some interesting templating languages that compile to increment DOM. It would be exciting to use them with Marionette for views that require fast rendering:

https://github.com/google/incremental-dom/blob/master/ECOSYSTEM.md

### CODE REVIEW

**Comment by paulfalgout** [comment]
note: babel-eslint broke the build here. https://github.com/eslint/eslint/issues/5476  Looks like that'll be fixed shortly and travis'll need to be re-run..  Or we can hard set the eslint dep

**Comment by paulfalgout** [comment]
I really like this, particularly considering the IDOM work being done.. this'll be an easy way to implement it even partially in legacy projects.
Your thoughts on something like this though?
```js
var html = this.renderHtml(template, data);

...
// override this for a custom renderer
renderHtml(template, data) {
  return Renderer.render(template, data, this);
}
```

**Comment by paulovieira** [comment]
Your suggestion makes the code more clean. On the other hand it's 1 more call in the stack when rendering. I like it both ways. Let's hear what other people have to say.

One other suggestion though: get rid of the `Renderer` object and module completely and move the code in `Renderer.render` to this new `renderHtml` method. It would make this new method a nice companion for the `attachElContent` and would make the overall strategy for custom rendering more consistent. 

```js
var View = Backbone.View.extend({

  ...

  // Render a template with data. The `template` parameter is
  // passed to the `TemplateCache` object to retrieve the
  // template function. Override this method to provide your own
  // custom rendering and template handling for all of Marionette.
  renderHtml: function(template, data) {
    if (!template) {
      throw new MarionetteError({
        name: 'TemplateNotFoundError',
        message: 'Cannot render the template since its false, null or undefined.'
      });
    }

    var templateFunc = _.isFunction(template) ? template : TemplateCache.get(template);

    return templateFunc(data);
  },

  attachElContent(html) {
    this.$el.html(html);

    return this;
  }

  ...
});
```

See also: #1968 and #2858

**Comment by paulovieira** [comment]
It seems the eslint has been fixed. Meanwhile this pull request has become outdated but I'll updated it. However I'd also like to have feedback about my last comment: what about get rid of the "Renderer" object and move the html rendering logic to a new "renderHtml" method?

Let's make marionette simpler!

**Comment by JSteunou** [comment]
Getting rid of Renderer.render now will be a breaking change. Maybe it's fine for v3. Just let the people know about it.

**Comment by paulovieira** [comment]
Yes, this pull request is for v3. It is definitely a breaking change. "Renderer" is present in marionette probably since its first day :-)

**Comment by ahumphreys87** [comment]
@paulovieira Im not sure I want to introduce such a big breaking change to v3 at this stage, we have now cut rc1.

A small break would be ok in my opinion but maybe removing the renderer should wait until the next major. We are aiming to do more regular major releases (which wont be as big as 3.0) from this point onwards.

Maybe a compromise would be to mark the Renderer as deprecated in 3.0 and implement @paulfalgout's suggestion? In the docs we could advise that this should be overridden rather than using a custom renderer class as the renderer will be removed in v4?

**Comment by paulfalgout** [comment]
I think that is a pretty sound suggestion.

**Comment by blikblum** [comment]
Until now i never needed to use a custom Renderer. But i'm wondering how would be implemented a global render strategy with the removal of Renderer?
Is there any example of custom Renderer in the wild?
I dont have a strong opinion favorable or against removal.

**Comment by ahumphreys87** [comment]
you make a good point @blikblum. Removing the Renderer would mean users having to do this on every view.

I think im :-1: for removing now

**Comment by rogovdm** [comment]
Currently I'm :-1: 

Not sure how to implement my global strategy without Render. I'm using it for my Hot Reloading module for a better development process.

And in my other project it is used because I have multiple template languages on a client :open_mouth: Useful during migration.

What is an alternative after removing Renderer, any thoughts?

**Comment by paulfalgout** [comment]
I think we can have all of it today, even deprecating the current renderer without removing it right away.

In order to set the renderer everywhere without the current renderer class you'd need to change the prototype of the views.  This certainly isn't a very nice way to go about updating the renderer and it has been [argued against previously](https://github.com/marionettejs/backbone.marionette/issues/1968#issuecomment-57957594).

So let's create a nicer interface for people to do this using the `classProperties` of [`Backbone.View#extend](http://backbonejs.org/#View-extend).

Such that:
```js
Marionette.View = Backbone.View.extend({ 
  /* all our view stuff */ 
  renderHtml(template, data) {
    return Renderer.render(template, data, this);
  }
 }, {
  setRenderer(renderer) {
    _.extend(Marionette.View.prototype, {
      renderHtml: renderer
    });
  }
});
```
This would mean an additional call in the stack for now, however you could quite easily remove that by
```js
Marionette.View.setRenderer(Marionette.Renderer.render);
Marionette.CollectionView.setRenderer(Marionette.Renderer.render);
```

Now while this would require 2 sets to replace it everywhere, I think this is ideal.  It may be very common in the future to want a different renderer for a CollectionView than a View.

In the future after we remove Marionette.Renderer and the default render can just be the `renderHtml` function.  Then the user can override it per view, or they can override it at a library level for View or CollectionView.

So hopefully this will open the door for.
```js
import IDomRender from 'marionette-idom';
Marionette.View.setRenderer(IDomRender);
```

And I think a single function interface off of the View class is simpler to understand and explain than the renderer class.

**Comment by paulovieira** [comment]
@paulfalgout Your approach is the best one so far! It makes a lot of sense to place this in the `classProperties`.

@ahumphreys87, I think you misunderstood the strategy here. People wouldn't have to define a render per view. A default one would always be there (the current one, based on `_.template`).

The main objective is to be able to define custom renderers for specific views, keeping some default renderer for all the other views.

**Comment by scott-w** [comment]
@paulfalgout @paulovieira What's the current status on this PR? I like the ideas behind it - do we try to get it into v3 or shall we put it into a v3.1, assuming this doesn't introduce breaking changes?

**Comment by paulovieira** [comment]
I haven't dedicated time to think about this, but I liked the last approach proposed by @paulfalgout (class properties). But I have some free time this weekend and I'll look at it again. 

Having custom renderers per view would add a lot of value to v3. One use very interesting use case is to use incremental dom templates to get better performance for views that are heavily used.

**Comment by ahumphreys87** [comment]
@paulovieira be great to see this work get merged. The use case of incremental dom is something im particularly interested in.

We've probably missed the cut off for v3 but if we can keep it non-breaking we can push out in a 3.x

**Pull request closed without merging**
