### PR TITLE
Remove bundled build

### PR DESCRIPTION
**Pull request by paulfalgout**
Resolves https://github.com/marionettejs/backbone.marionette/issues/2273

Essentially after removing `wreqr` and adding `radio` as an external dependency, we are requiring people loading with ye-ole-script-src to load other dependencies that do not get bundled.  Similarly if backbone-metal (https://github.com/marionettejs/backbone.marionette/issues/2426) is added it will be an additional base dependency.  And with https://github.com/marionettejs/backbone.marionette/issues/2312 babysitter may also get removed or swallowed, and thus the bundled `Mn` is not necessary or useful.

Initially my only goal was to remove the bundled build and traces of it, but I ran into a build issue, and I found some left over wreqr -> radio updates that were missing.

- [x] Remove some left-over Wreqr stuff from application
- [x] Remove controller.js from the build
- [x] Update bower/component to match (Resolves https://github.com/marionettejs/backbone.marionette/issues/2482)

### CODE REVIEW

**Comment by ahumphreys87** [comment]
Lgtm :+1:

**Comment by jasonLaster** [comment]
So first, Iike the three todos. And we should get those in there.

I'm not sure how I feel about removing a bundled option. The way I understand it, if we're using Mn specific 3rd parties (babysitter, metal, radio) then it's nice to offer a bundle of that stuff so that the lazy man can do

```html
<script src="mn.js"</script></script>win()</script>
```

thoughts?

**Comment by ahumphreys87** [comment]
Those were my initial concerns as well then I thought about how many people
actually load in the scripts like this? I don't think there will be many.

That said I'm now thinking even when using browserify would I rather just
load mn or load everything individually - Id probably go for the lazy
option.

I'm torn on this one, i don't think either way would effect my apps too
much and removing it will shrink the library down a bit but I can see why
it's useful to keep.

@paulfalgout what's you opinion? Do you have a motivation for pushing this
through?

**Comment by jasonLaster** [comment]
Yup, I like the marketing around browserify etc. like ppl just using it, not having to be too confused. With that said, great docs would solve this.

**Comment by paulfalgout** [comment]
We are already requiring people load dependencies.. underscore, backbone, jquery.

I don't know that we are helping too much by hiding away the other dependencies.  I think we are making it easier to not have to understand what is going on.

Specifically with a library like radio which appears to be gaining its own popularity, it is quite possible someone could be adding radio to their backbone project, prior to deciding to add marionette.  It is good to build that community as a separate entity that complements backbone.

While there may be reason to load backbone-metal as an included submodule vs an external dependency (I'd probably say the same for baby-sitter if it was a long-term solution) other libraries like radio that are not building blocks of Marionette should remain fairly external, which will make it easier if we do a switch in the future like Wreqr -> Radio.

Furthermore our libraries are put out on CDN.  For those that do load via script tags, this is a fairly likely scenario, but we're diluting the usefulness of the CDN by offering 2 versions.

Additionally we are complicating the build process which would make moving to modules and/or ES6 more difficult. 

I personally picked and use the bundled version at work as we don't yet have our build system ready for every project.  I picked it I suppose at the time because it seemed easier to not need to know what to upgrade when..  but it didn't make my getting started any faster.. I had to ask why it was bundled.. and figure out why there were multiple downloads.. if anything it was confusing.  I picked the bundled version initially because I assumed that the bundled version was safer and would make sure I did not have an incompatible version of wreqr or babysitter.  In reality Marionette follows semver and that was a mistaken concern.  

I think the multiple options for <script> tag users, while attempting to be helpful, are initially an added cognitive load for new users and only result in some incorrect assumptions.

The biggest reason I can see for having a bundled version is for js sandboxes.

Plus now that we are deprecating Marionette Modules and suggesting AMD/CJS etc, people not using a package manager will have to do something custom, or use the Marionette.Module shim.. yet another external dependency.

If we remove this, the download portion of the website becomes.
Download Marionette  (minified)

Dependncies you'll need:
jQuery
Underscore
Backbone
Backbone-Metal
Backbone.Radio

**Comment by ahumphreys87** [comment]
Ok I'm persuaded again, this gets my :+1: again :)

**Comment by jasonLaster** [comment]
@samccone thoughts?

Thanks for the writeup Paul. That helps a lot. I agree that it is good to simplify the build process.

**Comment by samccone** [comment]
I think many many people use the bundled build. It is simple and does not require multiple script tags. 

Sure we assume people have backbone (which requires jquery and underscore) but after that you just need Marionette (bundled) 

I think the install process for most people gets pretty gross when you start forcing them to put 3+ scripts for Marionette.

Clearly the more advanced users do not use the bundled version however I think that many people still do use that version, since it requires less thinking and is "easier" (it also does not require a build process which many people do not have on their projects)

Making things easier however is not always a good argument in this JS world of "quick start, easy, fast ect ect ect..." 

I am on the fence for this one.

:volcano:

**Pull request closed without merging**
