### PR TITLE
Don't rerender the entire CompositeView on sorting

### PR DESCRIPTION
**Pull request by Dremora**
Currently, every time a collection is sorted, the `CollectionView` calls `resortView` which in turn calls `_renderChildren`. It seems logical to do so, since `render` doesn't do much more than calling `_renderChildren`.

The same behavior is used for `CompositeView`: it calls `_sortView` which calls `_renderChildren` which in turn calls `render`. Out of these 3 methods, only `render` is reimplemented in `CompositeView`. Here it does much more - it re-renders not only the children, but also the entire template.

It doesn't make much sense to do so, re-rendering just children seems to be enough. And this is exactly what the `resortView` description suggests us to do (while incorrectly referring to `_renderChildren` as `renderChildren`).

I have replaced the call to `render` with the call to `_renderChildren` and removed part of the method description.

All tests still pass.

### CODE REVIEW

**Comment by samccone** [comment]
Seems quite reasonable to me :+1: 

@Dremora great research and write up. This is a big win for consistency as you said and makes a ton of sense when viewed in the larger context of the other view implementations and code paths.

**Comment by samccone** [comment]
ping @marionettejs/marionette-core

**Comment by ahumphreys87** [comment]
yup im good with this as well, nice catch @Dremora :+1:

**Comment by samccone** [comment]
~~great research and write up. This is a big win for consistency as you said and makes a ton of sense when viewed in the larger context of the other view implementations and code paths.~~

As pointed out by @ahumphreys87 this is actually a breaking change and something that we have talked about before

> CompositeViews are tricky tho..... since they render into the root element by default... So this change makes sense only if you are rendering into a custom container that we can clear out.

https://github.com/marionettejs/backbone.marionette/issues/1570#issuecomment-48221863

This change will be breaking to people who are not rendering into a container :|

**Comment by ahumphreys87** [comment]
@samccone although this does throw up an issue with our tests :) Ill create an issue and work on it

**Comment by Dremora** [comment]
I was suspecting there'll be a backwards compatibility issue, but wasn't sure where exactly.
With this taken into account, a possible solution could be, instead of modifying `resortView` in `CollectionView`, to reimplement it in `CompositeView` like this:
```javascript
  resortView: function() {
    if (Marionette.getOption(this, 'reorderOnSort')) {
      this.reorder();
    } else if (Marionette.getOption(containerView, 'childViewContainer')) {
      this._renderChildren();
    } else {
      this.render();
    }
  }
```

I can't however understand what exactly will break if we go ahead with the original solution. I couldn't extract a valid explanation from #1570. I've tried writing some tests and everything seems work work as expected (rendering a collection into root with a template present, then sorting, then comparing the HTML with the expected one). I'm hoping that the test implemented for #2334 will clarify it for me.

Also, the question asked by @MeoMix: should this be submitted as a PR for the `major` branch?

**Comment by ahumphreys87** [comment]
@Dremora Ive also had a go at creating a test but `_renderChildren` seems to work fine. Im :+1: for this change but would you mind adding a couple of things before we merge:

[] Update docs
[] Test to prove `CompositeView` still works without a `childViewContainer`

Something like this should do for the test:

```js
  describe('when sorting a CompositeView without a childViewContainer', function() {
    beforeEach(function() {
      this.compositeView = new this.CompositeView({
        childView: this.ChildView,
        collection: this.collection,
        template: _.template('<p>Hello</p>')
      });

      this.compositeView.render();

      this.model = new Backbone.Model({foo: '0', bar: '5'});
      this.collection.add(this.model);

      this.collection.comparator = 'foo';
      this.collection.sort();
    });

    it('should still render the markup of the template', function() {
      expect(this.compositeView.$el).to.have.$text('Hello0123');
    });
  });
```

**Comment by ahumphreys87** [comment]
@Dremora any progress on this?

**Comment by Dremora** [comment]
@ahumphreys87 not yet — but I'll try to finish it soon.

**Comment by jasonLaster** [comment]
rebase please @Dremora.

where's this at?

**Comment by ahumphreys87** [comment]
#closing in favour of #2411

**Pull request closed without merging**
