### PR TITLE
Add CollectionView live examples

### PR DESCRIPTION
**Pull request by denar90**
### Proposed changes
 - Add live examples for CollectionView doc
 - Improved a bit doc

Have some doubts about tree example ...

### CODE REVIEW

**Comment by scott-w** [comment]
Doubts as in whether it works or whether we should include it?

**Comment by denar90** [comment]
Changed a bit https://github.com/marionettejs/backbone.marionette/pull/3161/commits/86bc1ee755fdb4fe630beb650f80af46578c8ea7#diff-b35da3e415ba0f3de834402c5f82581cR1127

and here is template code 

```javascript
<script id="node-template" type="text/template">
    <%- nodeName %>
    <% if (nodes.length) { %>
    	<ul></ul>
    <% } %>
</script>
```

if it's fine for you then no doubts 😄

**Comment by rafde** [comment]
👍

**Comment by ahumphreys87** [comment]
👍

**Pull request merged**
