### PR TITLE
Doc linking fixes

### PR DESCRIPTION
**Pull request by paulfalgout**
Now that the website docs correctly convert .md to .html there is no need to link to .html.  Plus we can link directly to referenced portions of other documentation.

Some spell check.
Added underscore links on RegionManager

### CODE REVIEW

**Comment by jasonLaster** [comment]
:+1:

**Comment by samccone** [comment]
yeah this is great, thanks so much @paulfalgout 

I am going to put this into master thanks!

**Comment by paulfalgout** [comment]
Hmm yeah.. sorry about that, I did this work off a minor branch, and I think some of the updates are part of minor only documentation.  If you want I can split out the PRs?

**Comment by samccone** [comment]
yeah just saw that when i tried to cherry-pick :P

**Pull request merged**
