### PR TITLE
improve _createBuffer and attachBuffer in CollectionView and CompositeView

### PR DESCRIPTION
**Pull request by dkurucz**
follow up PR for #2500, sourcing branch "next" for these changes

...

opening PR against "next" instead of "master" #2396

fix for #2395

### CODE REVIEW

**Comment by ahumphreys87** [comment]
@dkurucz 1 last thing could you squash those 2 commits into 1? then this gets my :+1:

**Comment by dkurucz** [comment]
consolidated into one commit and pushed, no failures locally, so the build shouldn't be failing with underscore 1.6, not sure if the environment has a quirk that needs to be resolved (perhaps with the workspace?)

**Comment by dkurucz** [comment]
Hm, okay, there it goes

**Comment by jasonLaster** [comment]
:thumbsup:

**Pull request merged**
