### PR TITLE
Move Helpers into their own files

### LINKED ISSUE #2662: Move Helpers into their own files
We currently have many utils assigned in `helpers.js`. It'd be nice if they were each in their own file in a utils folder. An example of this would be `utils/isNodeAttached.js`. 

What needs to get done:
+ create files
+ update build / test files

### PR DESCRIPTION
**Pull request by pascalpp**
Resolves #2662

Created with @jdaudier at Marionette First Time Contributors Workshop!

img

h/t @jasonLaster

### CODE REVIEW

**Comment by jasonLaster** [comment]
Thanks guys!

**Comment by pascalpp** [comment]
img

**Comment by jdaudier** [comment]
giphy

**Comment by JSteunou** [comment]
Cant wait the Marionette Second Time Workshop :D

**Comment by jasonLaster** [comment]
Looks great. This will be  so nice as we modularize Marionette and classes can require the helpers that they need

**Comment by cmisenas** [comment]
Is there a filename convention that should be followed (`camelCaseFiles` vs `underscore_files`)?

**Comment by jdaudier** [comment]
@cmisenas We named the files the same as the method name, so if the method name started with an `_`, the file does too.  Open to suggestions if this doesn't make sense.

**Comment by pascalpp** [comment]
@cmisenas Yeah we just went with the convention of naming the file exactly the same as the method it attaches to the Marionette object. That means these filenames would maybe have to change if the method name changes, but I think that's probably a good thing, just for sake of clarity? @jdaudier @jasonLaster what do you think?

**Comment by jdaudier** [comment]
@pascalpp make sense to me.  if method name changes, file name also changes.

**Comment by ahumphreys87** [comment]
we should rename the specs as well I think. Move each to their own .spec.js file.

**Comment by jasonLaster** [comment]
@ahumphreys87 agreed, but I think that could be a new PR, this one is pretty significant and it could go stale without a merge

**Comment by paulfalgout** [comment]
The `/* jshint unused: false *//* global console */` don't need to be in each file.

**Comment by jdaudier** [comment]
@paulfalgout What does that line of comment do?  Is that just a reminder of the JSHint config?  Should we remove it from each of the method files?

**Comment by jdaudier** [comment]
@pascalpp Could you add me as a contributor to your fork, so I can make these edits and push to your fork > next branch?

**Comment by paulfalgout** [comment]
The global console one will be needed for whichever file console is in.   The other is removing jshint about unused variable..  Not sure exactly on that one, but it may be 1.. It may be none of them that need it.   But remove them all and selectively re-add one or the other as necessary..  Run grunt for jshint complaints

**Comment by pascalpp** [comment]
@paulfalgout I've removed those jshint directives. The only one that was needed was `global console` in `deprecate.js`.

@jdaudier Not sure how to add you, wanna show me?

**Comment by jdaudier** [comment]
thanks @pascalpp!

**Comment by pascalpp** [comment]
@paulfalgout @jasonLaster helpers.spec.js has three suites in it, for `isNodeAttached`, `normalizeUIKeys`, and `deprecate`. I'll go ahead and atomize those as well, into `test/unit/utils/*.spec.js`. Should I add pending (unimplemented) tests for the other utils?

**Comment by jdaudier** [comment]
@pascalpp I guess you can remove me as a collaborator now since you got everything updated.  :smiley:

**Comment by ahumphreys87** [comment]
manually merged into next, thanks @pascalpp

**Comment by jasonLaster** [comment]
Damnit @ahumphreys87, you beat me too it

**Pull request closed without merging**
