### PR TITLE
fix/improve coverage

### PR DESCRIPTION
**Pull request by elgubenis**
- when I ran gulp coverage it failed because estraverse-fb was missing
- improving coverage for Application Region

### CODE REVIEW

**Comment by paulfalgout** [comment]
:clap: Thanks for this.  I think if we can get the changes to `package.json` removed and a rebase and this is :+1:

**Comment by sethkrasnianski** [comment]
@elgubenis care to rebase :smile:?

**Comment by jasonLaster** [comment]
Yay coverage! Thanks for doing the hard work.

**Comment by paulfalgout** [comment]
Manually merged

**Pull request closed without merging**
