### PR TITLE
Rename Marionette.View to be Marionette.AbstractView.

### PR DESCRIPTION
**Pull request by jmeas**
WIP

Part 1 of #2251

Todo:
- Fix the few failing tests
- ~~Rename the spec files and update the spec-runner~~ the spec runner is gone apparently :see_no_evil:

### CODE REVIEW

**Comment by thejameskyle** [comment]
Fix the tests and lets merge today

**Comment by jmeas** [comment]
IM ON IT. Just wanted a good view of the diff to see what's going on.

**Comment by jmeas** [comment]
wat. Don't merge this yet..the tests are failing locally for me : [

**Comment by thejameskyle** [comment]
:+1:

**Comment by jmeas** [comment]
:+1:

**Comment by megawac** [comment]
:ship:

**Comment by samccone** [comment]
wow literally did not even look at this hahaha

**Comment by samccone** [comment]
:+1:

**Comment by thejameskyle** [comment]
> _toooodaaaaaaay_

**Comment by jmeas** [comment]
next up...LayoutView === ItemView!

**Comment by thejameskyle** [comment]
:tada:

**Pull request merged**
