### PR TITLE
lodash 4 support

### PR DESCRIPTION
**Pull request by megawac**
I think thats all that's needed for this repo (collection-method mixins may need another look). Dependent repos will also need to be looked at (Babysitter, backbone)

Also the travis-sh scripts will need to be added.

Tests still currently fail with this changeset using v4

### CODE REVIEW

**Comment by paulfalgout** [comment]
So for collection-method mixins.. do you think there'll be a way to keep support for pre & post v4 or are we just screwed?

This looks good though.

@ianmstew not sure how this might mess with what you're doing over on #2850

**Comment by megawac** [comment]
For the collection mixins we'll be running into the same issues backbone will with using lodash 4 and using lodash in general -- api contracts will be different

**Comment by paulfalgout** [comment]
but so it'll just be on the user to understand what functions are mixed in and what their API based on what `_` they load?  Or are there other issues?

**Comment by samccone** [comment]
question... does this change ever make sense until backbone has 4.0 support?

ps you will want to mod this file in the PR also
https://github.com/marionettejs/backbone.marionette/blob/master/.travis.yml#L20

**Comment by paulfalgout** [comment]
@samccone yeah so we really can't update travis until there's full support for v4 in backbone and the other dependencies.

**Comment by megawac** [comment]
@samccone backbone will support lodash 4 in v1.2.4 (coming soon™)

**Comment by samccone** [comment]
ok, lets xlink that PR here... and add it to the grid --- we will merge when it lands

**Comment by paulfalgout** [comment]
https://github.com/jashkenas/backbone/pull/3921 Changelog for 1.2.4

**Comment by jasonLaster** [comment]
:+1:

**Comment by paulfalgout** [comment]
BB 1.3.2 is out.
This'll need a rebase and likely a check of collectionview and region since quite a few changes went in.  Might as well bump bb for the v3 release.

**Comment by paulfalgout** [comment]
Ok this is GTG I think.  However we can't test lodash 4 yet in the matrix until we update that bash script as well as update the Mn tests and dependencies.

**Comment by samccone** [comment]
xref https://github.com/marionettejs/travis-ci-setup/pull/8

**Comment by paulfalgout** [comment]
This can probably be merged now and we can deal with the lodash compatibility of the dependencies and tests in another issue.  https://travis-ci.org/paulfalgout/backbone.marionette/jobs/115601113  We should just make sure these tests don't reflect anything missed in the library itself.

**Comment by paulfalgout** [comment]
Merging this and opening https://github.com/marionettejs/backbone.marionette/issues/2940

**Pull request merged**
