### PR TITLE
Update travis matrix to latest bb

### PR DESCRIPTION
**Pull request by denar90**
Link to the issue: #3115
@paulfalgout do we need to update `_` version to 1.8.3 or we can leave it at 1.8

### CODE REVIEW

**Comment by paulfalgout** [comment]
I think `1.8` will install `1.8.3` so that is ok.. Bb `1.3.1` however was buggy I think..  not sure we need to test against it.   But.. now something else is broken.. probably jsdom.. but not sure.. it _was_ working not too long ago.. so possibly a recent patch on a dependency broke something 😿

**Comment by denar90** [comment]
@paulfalgout so you think that 's why build is broken?

**Comment by rafde** [comment]
Please test for 1.3.3. All changes forward for collection will rely on 1.3.3 stuff.
There isn't even a changelog for 1.3.0 - 1.3.2, only 1.3.3 http://backbonejs.org/#changelog

**Comment by denar90** [comment]
Locally all tests are passed...

**Comment by rafde** [comment]
Yeah... but seems odd to test for a version that isn't canonical.

**Pull request merged**
