### PR TITLE
Add options hash into TemplateCache

### PR DESCRIPTION
**Pull request by Molchanov**
In one project I had a situation, when I needed to have options object in TemplateCache.prototype.loadTemplate function for loading template from different folders.

And I think that this simple modification will be very useful for others.

### CODE REVIEW

**Comment by samccone** [comment]
@thejameskyle @jmeas are you guys still ok with this PR?

**Comment by thejameskyle** [comment]
If it gets some tests. I'm good with it.

**Comment by samccone** [comment]
kk I will add them

**Comment by samccone** [comment]
moved to #2205

**Pull request closed without merging**
